// Auto-generated by @zerotal/core — do not edit manually.
// Regenerate with: bun zt route:types
//
// Every named route and the URL pattern it compiles to. `route()` reads this
// through declaration merging, so an unknown name or a missing :param is a
// compile error. Commit this file: editors and CI need it without booting the app.

export const ROUTES = {
  about: "/about",
  contact: "/contact",
  "contact.store": "/contact",
  "forgot-password": "/forgot-password",
  "forgot-password.store": "/forgot-password",
  home: "/",
  login: "/login",
  "login.store": "/login",
  "logout.store": "/logout",
  profile: "/profile",
  "profile.password.store": "/profile/password",
  "profile.store": "/profile",
  projects: "/projects",
  "projects.issues.edit.show": "/projects/:project/issues/:issue/edit",
  "projects.issues.edit.store": "/projects/:project/issues/:issue/edit",
  "projects.issues.new.show": "/projects/:project/issues/new",
  "projects.issues.new.store": "/projects/:project/issues/new",
  "projects.issues.show": "/projects/:project/issues/:issue",
  "projects.show": "/projects/:project",
  register: "/register",
  "register.store": "/register",
  "reset-password": "/reset-password",
  "reset-password.store": "/reset-password",
} as const;

/** The generated route table, as a type. */
export type Routes = typeof ROUTES;

declare module "@zerotal/core" {
  interface RouteRegistry extends Routes {}
}
