/**
 * ValidateSignatureMiddleware — rejects requests whose URL signature is
 * missing, tampered, or expired.
 *
 * Drop this in front of any route that uses signed URLs (magic links,
 * one-time invite links, email verification links generated by `Url.sign`).
 *
 * On failure it responds with a 403 JSON error.  Override `onInvalid()` in
 * a subclass if you need a different response (e.g. an HTML error page).
 *
 * @remarks
 * Fails **closed**: if no signing secret can be resolved (neither an explicit
 * `secret` option nor `config('app.key')`), it throws a `ConfigError` rather than
 * falling back to a guessable default and accepting forged links.
 *
 * @example
 * ```ts
 * // Static usage — reads APP_KEY from the container config:
 * Router.get('/auth/magic/verify', MagicController, 'verify', [ValidateSignatureMiddleware]);
 * ```
 *
 * @throws {ConfigError} When no signing secret is configured (missing `APP_KEY` / `app.key`).
 */

import { BaseMiddleware, ConfigError, type HttpContext, type NextFn } from "@zerotal/core";
import { Url } from "@zerotal/core/http";

interface Options {
  /** Override the secret used for verification. Defaults to config('app.key'). */
  secret?: string;
}

export class ValidateSignatureMiddleware extends BaseMiddleware<Options> {
  protected options: Options = {};

  async handle(http: HttpContext, next: NextFn): Promise<Response | void> {
    const secret = this.options.secret ?? this._resolveSecret(http);

    const fullUrl = http.request.url;

    if (!Url.verify(fullUrl, secret)) {
      return this.onInvalid(http);
    }

    return next();
  }

  /**
   * Called when the signature is invalid or the link has expired.
   * Override in a subclass to customise the error response.
   */
  protected onInvalid(_ctx: HttpContext): Response {
    return Response.json({ message: "This link is invalid or has expired." }, { status: 403 });
  }

  private _resolveSecret(ctx: HttpContext): string {
    let key: string | undefined;
    try {
      const config = (
        ctx.container as unknown as {
          container?: { tryMakeSync?(k: string): unknown };
        }
      )?.container?.tryMakeSync?.("config") as
        { get(k: string, fallback: string): string } | undefined;
      key = config?.get("app.key", "");
    } catch {
      key = undefined;
    }
    // Fail closed: never fall back to a guessable default secret. An unresolved
    // signing key means signatures cannot be verified safely, so surface a config
    // error instead of silently accepting forged links.
    if (!key) {
      throw new ConfigError(
        "ValidateSignatureMiddleware has no signing secret: set APP_KEY (config 'app.key') " +
          "or pass one explicitly via ValidateSignatureMiddleware.with({ secret }).",
      );
    }
    return key;
  }
}
