// Auto-generated by @zerotal/core — do not edit manually.
// Regenerate with: bun zt route:types
//
// Every named route and the URL pattern it compiles to. `route()` reads this
// through declaration merging, so an unknown name or a missing :param is a
// compile error. Commit this file: editors and CI need it without booting the app.

export const ROUTES = {
  "admin.posts": "/admin",
  "admin.posts.edit": "/admin/posts/:post/edit",
  "admin.posts.new": "/admin/posts/new",
  home: "/",
  "showcase.flow.ai-chat": "/showcase/flow/ai-chat",
  "showcase.flow.components": "/showcase/flow/components",
  "showcase.flow.counter": "/showcase/flow/counter",
  "showcase.flow.forms": "/showcase/flow/forms",
  "showcase.flow.headless": "/showcase/flow/headless",
  "showcase.flow.index": "/showcase/flow",
  "showcase.flow.islands": "/showcase/flow/islands",
  "showcase.flow.lists": "/showcase/flow/lists",
  "showcase.flow.live": "/showcase/flow/live",
  "showcase.flow.reorder": "/showcase/flow/reorder",
  "showcase.flow.streaming": "/showcase/flow/streaming",
  "showcase.flow.ui-kit": "/showcase/flow/ui-kit",
} as const;

/** The generated route table, as a type. */
export type Routes = typeof ROUTES;

declare module "@zerotal/core" {
  interface RouteRegistry extends Routes {}
}
