// Auto-generated by @zerotal/core — do not edit manually.
// Regenerate with: bun zt route:types
//
// Every named route, the URL pattern it compiles to, and the HTTP method it
// answers on. `route()` reads ROUTES through declaration merging, so an unknown
// name or a missing :param is a compile error; `action()` also reads METHODS, so
// a form cannot submit a route with the wrong verb.
// Commit this file: editors and CI need it without booting the app.

export const ROUTES = {
  "admin.posts": "/admin",
  "admin.posts.edit": "/admin/posts/:post/edit",
  "admin.posts.new": "/admin/posts/new",
  home: "/",
  "showcase.flow.ai-chat": "/showcase/flow/ai-chat",
  "showcase.flow.components": "/showcase/flow/components",
  "showcase.flow.counter": "/showcase/flow/counter",
  "showcase.flow.forms": "/showcase/flow/forms",
  "showcase.flow.headless": "/showcase/flow/headless",
  "showcase.flow.index": "/showcase/flow",
  "showcase.flow.islands": "/showcase/flow/islands",
  "showcase.flow.lists": "/showcase/flow/lists",
  "showcase.flow.live": "/showcase/flow/live",
  "showcase.flow.reorder": "/showcase/flow/reorder",
  "showcase.flow.streaming": "/showcase/flow/streaming",
  "showcase.flow.ui-kit": "/showcase/flow/ui-kit",
} as const;

export const METHODS = {
  home: "GET",
  "showcase.flow.ai-chat": "GET",
  "showcase.flow.components": "GET",
  "showcase.flow.counter": "GET",
  "showcase.flow.forms": "GET",
  "showcase.flow.headless": "GET",
  "showcase.flow.index": "GET",
  "showcase.flow.islands": "GET",
  "showcase.flow.lists": "GET",
  "showcase.flow.live": "GET",
  "showcase.flow.reorder": "GET",
  "showcase.flow.streaming": "GET",
  "showcase.flow.ui-kit": "GET",
} as const;

/** The generated route table, as a type. */
export type Routes = typeof ROUTES;

/** The HTTP method each named route answers on. */
export type RouteMethods = typeof METHODS;

declare module "@zerotal/core" {
  interface RouteRegistry extends Routes {}
  interface RouteMethodRegistry extends RouteMethods {}
}
