// Auto-generated by @zerotal/core — do not edit manually.
// Regenerate with: bun zt route:types
//
// Every named route, the URL pattern it compiles to, and the HTTP method it
// answers on. `route()` reads ROUTES through declaration merging, so an unknown
// name or a missing :param is a compile error; `action()` also reads METHODS, so
// a form cannot submit a route with the wrong verb.
// Commit this file: editors and CI need it without booting the app.

export const ROUTES = {
  about: "/about",
  contact: "/contact",
  "forgot-password": "/forgot-password",
  "forgot-password.store": "/forgot-password",
  home: "/",
  login: "/login",
  "login.store": "/login",
  "logout.store": "/logout",
  profile: "/profile",
  "profile.password.store": "/profile/password",
  "profile.store": "/profile",
  register: "/register",
  "register.store": "/register",
  "reset-password": "/reset-password",
  "reset-password.store": "/reset-password",
} as const;

export const METHODS = {
  about: "GET",
  contact: "GET",
  "forgot-password": "GET",
  "forgot-password.store": "POST",
  home: "GET",
  login: "GET",
  "login.store": "POST",
  "logout.store": "POST",
  profile: "GET",
  "profile.password.store": "POST",
  "profile.store": "POST",
  register: "GET",
  "register.store": "POST",
  "reset-password": "GET",
  "reset-password.store": "POST",
} as const;

/** The generated route table, as a type. */
export type Routes = typeof ROUTES;

/** The HTTP method each named route answers on. */
export type RouteMethods = typeof METHODS;

declare module "@zerotal/core" {
  interface RouteRegistry extends Routes {}
  interface RouteMethodRegistry extends RouteMethods {}
}
