/**
 * Writes `types/routes.generated.ts` — the name → URL pattern map that makes
 * `route()` type-checked.
 *
 * The map is read from a **booted application's** `Router.namedRoutes`, never
 * from the filesystem. Route names come from three places and only one of them
 * is a file path: the file-router's naming convention, an explicit
 * `export const meta = { GET: { name } }`, and programmatic registrations
 * (`Router.get(path, C, 'name')`, a provider's `Router.group()`, Flow's file
 * routes). A globber would see the first and miss the other two, and a second
 * implementation of the naming rules is a second implementation to disagree
 * with the first. Booting makes the generated file true by construction — it is
 * the same map `route()` reads at runtime.
 *
 * The emitted shape is data, not code:
 *
 * ```ts
 * export const ROUTES = { "posts.show": "/posts/:slug" } as const;
 * ```
 *
 * one line per route, so adding a param changes one string rather than
 * regenerating a function per route. Params are derived from the pattern by
 * `ParamsOf` (see `registry.ts`), and the same plain object is importable from
 * the browser bundle.
 */
import { relative } from "node:path";

/** Where the generated map is written, relative to the project root. */
export const ROUTE_TYPES_FILE = "types/routes.generated.ts";

const HEADER = [
  "// Auto-generated by @zerotal/core — do not edit manually.",
  "// Regenerate with: bun zt route:types",
  "//",
  "// Every named route and the URL pattern it compiles to. `route()` reads this",
  "// through declaration merging, so an unknown name or a missing :param is a",
  "// compile error. Commit this file: editors and CI need it without booting the app.",
  "",
];

/**
 * Render the contents of `types/routes.generated.ts` from a name → pattern map.
 *
 * Names are sorted so the file is stable across boots — provider registration
 * order is not, and an unstable generated file shows up as noise in every diff
 * and as a false failure in `--check`.
 *
 * @param namedRoutes - The router's `namedRoutes` map (name → URL pattern).
 * @param importSpecifier - Module to augment. Defaults to `@zerotal/core`; apps that import the framework through the `zerotal` meta-package still augment core, since that is where `RouteRegistry` is declared.
 * @returns The full file contents, ending in a newline.
 */
export function generateRouteTypes(
  namedRoutes: ReadonlyMap<string, string>,
  importSpecifier = "@zerotal/core",
): string {
  const entries = Array.from(namedRoutes.entries()).sort(([a], [b]) => a.localeCompare(b));

  // Quote the key only when it isn't a bare identifier — `home` stays bare and
  // `posts.show` stays quoted, which is what a formatter would do to this file
  // anyway. Matching it here keeps `format:check` off a file nobody edits.
  const lines = entries.map(
    ([name, pattern]) =>
      `  ${/^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name)}: ` +
      `${JSON.stringify(pattern)},`,
  );

  // Empty on one line: an app with no named routes still gets a file a formatter
  // leaves alone (and a registry that types nothing, so `route()` stays on its
  // untyped overload).
  const table =
    lines.length > 0
      ? ["export const ROUTES = {", ...lines, "} as const;"]
      : ["export const ROUTES = {} as const;"];

  return [
    ...HEADER,
    ...table,
    "",
    "/** The generated route table, as a type. */",
    "export type Routes = typeof ROUTES;",
    "",
    `declare module ${JSON.stringify(importSpecifier)} {`,
    "  interface RouteRegistry extends Routes {}",
    "}",
    // The file is rewritten on every dev boot; without a trailing newline a
    // formatter in the app would put one back, forever.
    "",
  ].join("\n");
}

/** Outcome of {@link writeRouteTypes}. */
export interface RouteTypesResult {
  /** Project-relative path of the generated file. */
  path: string;
  /** The contents that should be on disk. */
  content: string;
  /** True when the file on disk differed (or was missing) — i.e. the write changed something. */
  changed: boolean;
  /** How many named routes were written. */
  count: number;
}

/**
 * Write (or, with `check`, verify) `types/routes.generated.ts` for a booted app.
 *
 * @param namedRoutes - The router's `namedRoutes` map.
 * @param options - `cwd` (project root, default `process.cwd()`) and `check` (compare only, never write).
 * @returns Whether the on-disk file was stale, plus the contents it should have.
 */
export async function writeRouteTypes(
  namedRoutes: ReadonlyMap<string, string>,
  options: { cwd?: string; check?: boolean } = {},
): Promise<RouteTypesResult> {
  const cwd = options.cwd ?? process.cwd();
  const content = generateRouteTypes(namedRoutes);
  const target = `${cwd}/${ROUTE_TYPES_FILE}`;

  const file = Bun.file(target);
  const existing = (await file.exists()) ? await file.text() : null;
  const changed = existing !== content;

  if (changed && options.check !== true) {
    await Bun.write(target, content);
  }

  return {
    path: relative(cwd, target).replace(/\\/g, "/"),
    content,
    changed,
    count: namedRoutes.size,
  };
}
