// Auto-generated by @zerotal/inertia — do not edit manually.
// Regenerate with: bun zt inertia:build
//
// IMPORTANT: These are dynamic import THUNKS, not static imports.
// Bun.build with splitting:true creates one .js chunk per page.
// Converting to static imports will bundle ALL pages into app.js.

export const pages: Record<string, () => Promise<{ default: unknown }>> = {
  about: () => import("./pages/about.tsx"),
  contact: () => import("./pages/contact.tsx"),
  error: () => import("./pages/error.tsx"),
  "forgot-password": () => import("./pages/forgot-password.tsx"),
  home: () => import("./pages/home.tsx"),
  login: () => import("./pages/login.tsx"),
  profile: () => import("./pages/profile.tsx"),
  register: () => import("./pages/register.tsx"),
  "reset-password": () => import("./pages/reset-password.tsx"),
};
