// Auto-generated by @zerotal/inertia — do not edit manually.
// Regenerate with: bun zt inertia:build
//
// IMPORTANT: These are dynamic import THUNKS, not static imports.
// Bun.build with splitting:true creates one .js chunk per page.
// Converting to static imports will bundle ALL pages into app.js.

export const pages = {
  about: () => import("./pages/about.tsx"),
  contact: () => import("./pages/contact.tsx"),
  error: () => import("./pages/error.tsx"),
  "forgot-password": () => import("./pages/forgot-password.tsx"),
  home: () => import("./pages/home.tsx"),
  login: () => import("./pages/login.tsx"),
  profile: () => import("./pages/profile.tsx"),
  register: () => import("./pages/register.tsx"),
  "reset-password": () => import("./pages/reset-password.tsx"),
  "projects/index": () => import("./pages/projects/index.tsx"),
  "projects/show": () => import("./pages/projects/show.tsx"),
  "issues/form": () => import("./pages/issues/form.tsx"),
  "issues/show": () => import("./pages/issues/show.tsx"),
} satisfies Record<string, () => Promise<{ default: unknown }>>;

// Type-only: lets a controller's `Inertia.render(name, props)` be checked
// against the props each page component declares. Erased at runtime — and
// it is the ONLY place the server side touches the client component graph.
declare module "@zerotal/inertia" {
  interface InertiaPageRegistry {
    pages: typeof pages;
  }
}
