import { describe, it, expect } from "bun:test";
import * as barrel from "./index.ts";

// Frozen kernel surface. The root `@zerotal/core` barrel is intentionally lean:
// heavy or cohesive subsystems live behind explicit subpaths (`@zerotal/core/carbon`,
// `/http`, `/view`, `/env`, `/config`, `/security`, `/dev`, `/assets`, `/health`,
// `/metrics`). This guard stops the barrel from silently re-growing into a god-module.
//
// If this test fails:
//   • You added a symbol that belongs to a subsystem → export it from that subpath's
//     `index.ts` instead of the root barrel.
//   • You deliberately grew the kernel → add the name here, on purpose.
// (Type-only exports are invisible at runtime and are not listed here.)
const KERNEL_EXPORTS = [
  "App",
  "AppBooted",
  "Application",
  "Artisan",
  "BadRequestError",
  "BaseMiddleware",
  "BindingNotFoundError",
  "BufferWriter",
  "CallQueuedListener",
  "Collection",
  "Command",
  "CommandRan",
  "CommandRunner",
  "Config",
  "ConfigError",
  "ConflictError",
  "Container",
  "ContainerLockedError",
  "CorsMiddleware",
  "Emitter",
  // Deliberate kernel addition: the emitter it stands in for is here too, and a
  // fake that is harder to import than the thing it fakes does not get used.
  "EventFake",
  "Events",
  "ExceptionHandler",
  "Fluent",
  "ForbiddenError",
  "FrameworkEvents",
  "GoneError",
  "HttpContext",
  "HttpError",
  "ZerotalError",
  "LimiterDefinition",
  "MarkdownBuilder",
  "MethodNotAllowedError",
  "MiddlewareSkipped",
  "NotFoundError",
  "OutgoingRequestCompleted",
  "Pipeline",
  "RateLimiter",
  "RedirectBuilder",
  "RequestContext",
  "RequestFailed",
  "RequestHandled",
  "ResourceRouteBuilder",
  "ResponseBuilder",
  "Router",
  "RouterState",
  "ScopedResolver",
  "SecureHeadersMiddleware",
  "ServiceProvider",
  "ServiceUnavailableError",
  "Str",
  "TerminalWriter",
  "ThrottleMiddleware",
  "TooManyRequestsError",
  "UnauthorizedError",
  "UnprocessableEntityError",
  "ValidationError",
  "WebhookMiddleware",
  "abort",
  "app",
  "basePath",
  "buildCookie",
  "camelCase",
  "collect",
  "config",
  "createFacade",
  "currentApp",
  "currentPage",
  "data_get",
  "deepMerge",
  "devSurfacesEnabled",
  "env",
  "file",
  "fluent",
  "hmacHex",
  "html",
  "inject",
  "isDevSurfaceAllowed",
  "json",
  "make",
  "markdown",
  "parseCookieHeader",
  "pageElements",
  "pipe",
  "pipeAsync",
  "pluralize",
  "readCookie",
  "redirect",
  "redirectTo",
  "registerAppScope",
  "registerFileRouteResolver",
  "request",
  "requireEnv",
  "rescue",
  "rescueSync",
  "route",
  "safeEqual",
  "safeRedirectPath",
  "scanFileRoutes",
  "setAppEnv",
  "setCurrentPageResolver",
  "setImplicitModelResolver",
  "sha256Hex",
  "singularize",
  "snakeCase",
  "startZerotal",
  "tableNameFor",
  "tap",
  "tapAsync",
  "tryCurrentApp",
  "view",
  "withApp",
  "withHeaders",
].sort();

describe("core barrel surface", () => {
  it("exports only the frozen lean kernel set (no silent re-growth)", () => {
    expect(Object.keys(barrel).sort()).toEqual(KERNEL_EXPORTS);
  });
});
