// Auto-generated by @zerotal/inertia — do not edit manually.
// Regenerate with: bun zt inertia:build
//
// IMPORTANT: These are dynamic import THUNKS, not static imports.
// Bun.build with splitting:true creates one .js chunk per page.
// Converting to static imports will bundle ALL pages into app.js.

export const pages = {
  about: () => import("./pages/about.vue"),
  contact: () => import("./pages/contact.vue"),
  error: () => import("./pages/error.vue"),
  "forgot-password": () => import("./pages/forgot-password.vue"),
  home: () => import("./pages/home.vue"),
  login: () => import("./pages/login.vue"),
  profile: () => import("./pages/profile.vue"),
  register: () => import("./pages/register.vue"),
  "reset-password": () => import("./pages/reset-password.vue"),
} satisfies Record<string, () => Promise<{ default: unknown }>>;

// Type-only: lets a controller's `Inertia.render(name, props)` be checked
// against the props each page component declares. Erased at runtime — and
// it is the ONLY place the server side touches the client component graph.
declare module "@zerotal/inertia" {
  interface InertiaPageRegistry {
    pages: typeof pages;
  }
}
