// Auto-generated by @zerotal/inertia — do not edit manually.
// Regenerate with: bun zt inertia:build
//
// IMPORTANT: These are dynamic import THUNKS, not static imports.
// Bun.build with splitting:true creates one .js chunk per page.
// Converting to static imports will bundle ALL pages into app.js.

export const pages: Record<string, () => Promise<{ default: unknown }>> = {
  about: () => import("./pages/about.vue"),
  contact: () => import("./pages/contact.vue"),
  error: () => import("./pages/error.vue"),
  "forgot-password": () => import("./pages/forgot-password.vue"),
  home: () => import("./pages/home.vue"),
  login: () => import("./pages/login.vue"),
  profile: () => import("./pages/profile.vue"),
  register: () => import("./pages/register.vue"),
  "reset-password": () => import("./pages/reset-password.vue"),
};
