/**
 * Scans the configured pages directory (default `resources/js/pages`) for
 * `**\/*.tsx` using Bun.Glob and generates `resources/js/pages.generated.ts` —
 * a file of dynamic import thunks.
 *
 * Bun.build with splitting:true recognises dynamic import() calls and
 * automatically creates a separate .js chunk per page component.
 * Users download only the chunk for the page they are visiting.
 *
 * The directory is configurable via `inertia.pagesDir` in config/inertia.ts.
 * Import paths in the generated file are computed relative to the generated
 * file's own location (`resources/js/`), so any pages directory works.
 *
 * Run via: bun zt inertia:build
 * Or automatically during InertiaProvider.onBooted() in production.
 */
import { config } from "@zerotal/core";
import { frameworkLog } from "@zerotal/core/logger";
import { relative } from "node:path";
import { DEFAULT_PAGES_DIR } from "./config.ts";

// The generated registry always lives alongside app.tsx so it can be imported
// from there. Import specifiers are resolved relative to this directory.
const GENERATED_DIR = "resources/js";
const GENERATED_FILE = `${GENERATED_DIR}/pages.generated.ts`;

/**
 * Scan the pages directory and (re)write `resources/js/pages.generated.ts`, a map of
 * page name → dynamic `import()` thunk that `Bun.build({ splitting: true })` turns into
 * one lazy-loaded chunk per page. Called by the `inertia:build` / `make:page` commands
 * and by `InertiaProvider` at boot in production.
 *
 * @param cwd - Project root to scan and write relative to. Defaults to `process.cwd()`.
 * @param pagesDir - Pages directory relative to `cwd`. Defaults to the `inertia.pagesDir` config (`resources/js/pages`).
 * @returns Resolves once the registry file has been written.
 * @internal Framework scaffolding; not called from application code.
 */
export async function generatePageRegistry(
  cwd = process.cwd(),
  pagesDir: string = config.safe("inertia.pagesDir", DEFAULT_PAGES_DIR),
): Promise<void> {
  // Normalise to a cwd-relative POSIX path without a trailing slash.
  const dir = pagesDir.replace(/\\/g, "/").replace(/\/+$/, "");

  // Import base is the path from the generated file's directory to the pages
  // directory, e.g. 'resources/js' → 'resources/js/pages' yields 'pages',
  // and 'resources/js' → 'resources/pages' yields '../pages'.
  const importBase = relative(GENERATED_DIR, dir).replace(/\\/g, "/") || ".";

  // Match both React/JSX pages (.tsx) and Vue Single-File Components (.vue).
  const glob = new Bun.Glob(`${dir}/**/*.{tsx,vue}`);
  const thunks: string[] = [];

  for await (const file of glob.scan({ cwd })) {
    const normalised = file.replace(/\\/g, "/"); // normalise Windows backslashes

    // 'resources/js/pages/Users/Index.tsx' → 'Users/Index' (extension dropped
    // for the registry key, but preserved in the import specifier below).
    const rel = normalised.slice(dir.length + 1); // strip the pages directory prefix
    const name = rel.replace(/\.(tsx|vue)$/, "");

    // Build a relative specifier (with its real extension); ensure a leading
    // './' for same/child dirs so Bun resolves it and the .vue loader can fire.
    const importPath = `${importBase}/${rel}`;
    const specifier = importPath.startsWith(".") ? importPath : `./${importPath}`;

    // Quote the key only when it isn't a bare identifier — a nested page yields
    // `Users/Index`, which has to stay quoted to be valid.
    const key = /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);

    // Dynamic thunk — NOT `import X from '...'`
    // Bun splits each of these into a separate .js chunk automatically
    thunks.push(`  ${key}: () => import(${JSON.stringify(specifier)}),`);
  }

  if (thunks.length === 0) {
    frameworkLog("inertia").warn("No page components found", { dir });
  }

  const content = [
    "// Auto-generated by @zerotal/inertia — do not edit manually.",
    "// Regenerate with: bun zt inertia:build",
    "//",
    "// IMPORTANT: These are dynamic import THUNKS, not static imports.",
    "// Bun.build with splitting:true creates one .js chunk per page.",
    "// Converting to static imports will bundle ALL pages into app.js.",
    "",
    "export const pages: Record<string, () => Promise<{ default: unknown }>> = {",
    ...thunks,
    "};",
    // Trailing newline: the file is written on every dev rebuild, and without it
    // a formatter in the app would rewrite it right back, forever.
    "",
  ].join("\n");

  await Bun.write(`${cwd}/${GENERATED_FILE}`, content);

  frameworkLog("inertia").info(`Generated page registry: ${thunks.length} pages`, {
    pages: thunks.length,
  });
}
