export const firstNames = [
  "John",
  "Peter",
  "David",
  "Michael",
  "James",
  "William",
  "Charles",
  "George",
  "Joseph",
  "Richard",
  "Edward",
  "Thomas",
  "Arthur",
  "Robert",
  "Henry",
  "Harry",
  "Frank",
  "Albert",
  "Walter",
  "Harold",
  "Mary",
  "Elizabeth",
  "Margaret",
  "Sarah",
  "Jane",
  "Emily",
  "Emma",
  "Susan",
  "Catherine",
  "Ann",
  "Florence",
  "Alice",
  "Annie",
  "Ellen",
  "Clara",
  "Edith",
  "Grace",
  "Lily",
  "Rose",
  "Bessie",
  "Jack",
  "Oliver",
  "Jacob",
  "Charlie",
  "Oscar",
  "Amelia",
  "Olivia",
  "Isla",
  "Poppy",
  "Ava",
  "Isabella",
  "Jessica",
  "Sophie",
  "Johan",
  "Pieter",
  "Willem",
  "Hendrik",
  "Johannes",
  "Christiaan",
  "Charl",
  "Francois",
  "Jaco",
  "Ruan",
  "Morne",
  "Cobus",
  "Hennie",
  "Barend",
  "Stephan",
  "Gerhard",
  "Marius",
  "Deon",
  "Dawid",
  "Ryno",
  "Anzel",
  "Annalie",
  "Marinda",
  "Liezel",
  "Riana",
  "Yolandi",
  "Sunette",
  "Elize",
  "Corlia",
  "Zelda",
  "Dirk",
  "Schalk",
  "Lourens",
  "Andries",
  "Anton",
  "Christo",
  "Ettienne",
  "Frikkie",
  "Gerrit",
  "Hugo",
  "Ignatius",
  "Jacques",
  "Kobus",
  "Leon",
  "Nico",
  "Ockert",
  "Peet",
  "Quintin",
  "Riaan",
  "Tiaan",
  "Sipho",
  "Thandi",
  "Mandla",
  "Sizwe",
  "Lindiwe",
  "Bongi",
  "Nomsa",
  "Zandile",
  "Gugu",
  "Zanele",
  "Vusi",
  "Jabu",
  "Musa",
  "Sfiso",
  "Sibusiso",
  "Bongani",
  "Sandile",
  "Ndumiso",
  "Xolani",
  "Nkosi",
  "Mpumi",
  "Buhle",
  "Zizipho",
  "Akhona",
  "Yandisa",
  "Liyema",
  "Bandile",
  "Olwethu",
  "Amahle",
  "Nontobeko",
  "Phumzile",
  "Nompumelelo",
  "Nonhlanhla",
  "Slindile",
  "Hlengiwe",
  "Zinhle",
  "Nosipho",
  "Noxolo",
  "Nqobile",
  "Sinenhlanhla",
  "Nokuthula",
  "Samkelisiwe",
  "Nolwazi",
  "Gugulethu",
  "Gcinile",
  "Celiwe",
  "Busisiwe",
  "Ayanda",
  "Asanda",
  "Aphiwe",
  "Andisiwe",
  "Alizwa",
  "Babalwa",
  "Bulelwa",
  "Bongiwe",
  "Bathandwa",
  "Chuma",
  "Cikizwa",
  "Cwenga",
  "Khanyisa",
  "Kholeka",
  "Khumbuzile",
  "Lindelwa",
  "Liyabona",
  "Loyiso",
  "Lulama",
  "Lwazi",
  "Mandisa",
  "Mbalentle",
  "Mihlali",
  "Nwabisa",
  "Ncediswa",
  "Ndileka",
  "Nomhle",
  "Nonceba",
  "Nondumiso",
  "Nozuko",
  "Phumla",
  "Qaqamba",
  "Sibabalwe",
  "Siphokazi",
  "Sisipho",
  "Somikazi",
  "Thobeka",
  "Thumeka",
  "Vuyelwa",
  "Vuyiseka",
  "Xabiso",
  "Xoliswa",
  "Yolisa",
  "Thabo",
  "Lerato",
  "Kabelo",
  "Tshepo",
  "Lebo",
  "Mpho",
  "Nthabiseng",
  "Refilwe",
  "Kopano",
  "Palesa",
  "Kagiso",
  "Katlego",
  "Tshegofatso",
  "Amogelang",
  "Dikeledi",
  "Khaya",
  "Onalerona",
  "Oarabile",
  "Lesego",
  "Bokamoso",
  "Kgomotso",
  "Kamogelo",
  "Thato",
  "Odirile",
  "Neo",
  "Rethabile",
  "Tshepiso",
  "Karabo",
  "Teboho",
  "Dimpho",
  "Kutlwano",
  "Reabetswe",
  "Tumelo",
  "Boitumelo",
  "Ofentse",
  "Gomolemo",
  "Kganya",
  "Mahlatse",
  "Mologadi",
  "Makgabo",
  "Noko",
  "Ngoako",
  "Lesiba",
  "Matome",
  "Tlou",
  "Tau",
  "Koko",
  "Mmakgabo",
  "Puleng",
  "Tumi",
  "Ntsako",
  "Rirhandzu",
  "Xitshembiso",
  "Vutlhari",
  "Ntshembo",
  "Tintswalo",
  "Nyeleti",
  "Hlulani",
  "Akani",
  "Kurhula",
  "Masingita",
  "Pfano",
  "Khathu",
  "Mutali",
  "Tshilidzi",
  "Rendani",
  "Mashudu",
  "Ndivhuwo",
  "Rofhiwa",
  "Takalani",
  "Matthew",
  "Anthony",
  "Mark",
  "Steven",
  "Paul",
  "Andrew",
  "Kenneth",
  "Joshua",
  "Kevin",
  "Brian",
  "Timothy",
  "Ronald",
  "Jason",
  "Jeffrey",
  "Ryan",
  "Gary",
  "Nicholas",
  "Eric",
  "Stephen",
  "Larry",
  "Justin",
  "Scott",
  "Brandon",
  "Benjamin",
  "Samuel",
  "Gregory",
  "Alexander",
  "Patrick",
  "Raymond",
  "Dennis",
  "Jerry",
  "Tyler",
  "Aaron",
  "Jose",
  "Adam",
  "Nathan",
  "Douglas",
  "Zachary",
  "Kyle",
  "Ethan",
  "Noah",
  "Jeremy",
  "Christian",
  "Keith",
  "Roger",
  "Terry",
  "Gerald",
  "Sean",
  "Austin",
  "Carl",
  "Lawrence",
  "Dylan",
  "Jesse",
  "Jordan",
  "Bryan",
  "Billy",
  "Joe",
  "Bruce",
  "Gabriel",
  "Logan",
  "Willie",
  "Alan",
  "Juan",
  "Wayne",
  "Elijah",
  "Randy",
  "Roy",
  "Vincent",
  "Ralph",
  "Eugene",
  "Russell",
  "Bobby",
  "Mason",
  "Philip",
  "Louis",
  "Patricia",
  "Jennifer",
  "Linda",
  "Barbara",
  "Karen",
  "Lisa",
  "Nancy",
  "Betty",
  "Sandra",
  "Ashley",
  "Kimberly",
  "Donna",
  "Michelle",
  "Carol",
  "Amanda",
  "Dorothy",
  "Melissa",
  "Deborah",
  "Stephanie",
  "Rebecca",
  "Sharon",
  "Laura",
  "Cynthia",
  "Kathleen",
  "Amy",
  "Angela",
  "Shirley",
  "Anna",
  "Brenda",
  "Pamela",
  "Nicole",
  "Samantha",
  "Katherine",
  "Christine",
  "Debra",
  "Rachel",
  "Carolyn",
  "Janet",
  "Maria",
  "Heather",
  "Diane",
  "Ruth",
  "Julie",
  "Joyce",
  "Virginia",
  "Victoria",
  "Kelly",
  "Lauren",
  "Christina",
  "Joan",
  "Evelyn",
  "Judith",
  "Megan",
  "Andrea",
  "Cheryl",
  "Hannah",
  "Jacqueline",
  "Martha",
  "Gloria",
  "Teresa",
  "Sara",
  "Madison",
  "Frances",
  "Kathryn",
  "Janice",
  "Jean",
  "Abigail",
  "Julia",
  "Judy",
  "Sophia",
  "Stephanus",
  "Gert",
  "Adriaan",
  "Petrus",
  "Karel",
  "Lodewyk",
  "Bernardus",
  "Nicolaas",
  "Jan",
  "Johanna",
  "Magdalena",
  "Catharina",
  "Susanna",
  "Cornelia",
  "Helena",
  "Jacoba",
  "Aletta",
  "Margaretha",
  "Siphesihle",
  "Lethabo",
  "Melokuhle",
  "Banele",
  "Lubabalo",
  "Siyabonga",
  "Thabiso",
  "Lebogang",
  "Tebogo",
  "Itumeleng",
  "Olebogeng",
  "Otlhile",
  "Kelebogile",
  "Tshepang",
  "Bontle",
  "Keabetswe",
  "Tlhalefang",
  "Tshenolo",
  "Onthatile",
  "Rebaone",
  "Gaopalelwe",
];

export const lastNames = [
  "Dlamini",
  "Ndlovu",
  "Khumalo",
  "Sithole",
  "Mokoena",
  "Nkosi",
  "Zungu",
  "Zwane",
  "Mkhize",
  "Mthembu",
  "Gumede",
  "Mahlangu",
  "Ngcobo",
  "Maseko",
  "Mabaso",
  "Thabethe",
  "Nzimande",
  "Hadebe",
  "Cele",
  "Xaba",
  "Sibiya",
  "Mnguni",
  "Buthelezi",
  "Nxumalo",
  "Shabalala",
  "Zikalala",
  "Makhanya",
  "Nkabinde",
  "Mzizi",
  "Bhengu",
  "Nyawo",
  "Mchunu",
  "Mvelase",
  "Ntuli",
  "Phungula",
  "Mncube",
  "Mdlalose",
  "Luthuli",
  "Mbuyisa",
  "Ndimande",
  "Shange",
  "Majola",
  "Zondi",
  "Mbanjwa",
  "Ndlela",
  "Mlambo",
  "Ngubane",
  "Makhoba",
  "Maphumulo",
  "Masango",
  "Shabangu",
  "Mkhwanazi",
  "Xulu",
  "Zitha",
  "Vilakazi",
  "Zikhali",
  "Hlatshwayo",
  "Hlongwane",
  "Nene",
  "Mbatha",
  "Mofokeng",
  "Motloung",
  "Motaung",
  "Moloi",
  "Letsoalo",
  "Modise",
  "Molefe",
  "Moroke",
  "Mphahlele",
  "Phiri",
  "Seabi",
  "Sebokedi",
  "Sekgobela",
  "Tladi",
  "Tshabalala",
  "Mokgotha",
  "Mokwena",
  "Radebe",
  "Mohlala",
  "Phakathi",
  "Kekana",
  "Ledwaba",
  "Makgoba",
  "Mabunda",
  "Baloyi",
  "Maluleke",
  "Chauke",
  "Mathebula",
  "Shirinda",
  "Makhubela",
  "Mahomed",
  "Patel",
  "Naidoo",
  "Moodley",
  "Govender",
  "Pillay",
  "Chetty",
  "Reddy",
  "Desai",
  "Singh",
  "Khan",
  "Ismail",
  "Moosa",
  "Ebrahim",
  "Saloojee",
  "Mitha",
  "Chohan",
  "Seedat",
  "Cassim",
  "Mia",
  "Allie",
  "Abrahams",
  "Hendricks",
  "Jacobs",
  "Petersen",
  "Isaacs",
  "Adams",
  "Arendse",
  "Cupido",
  "Goliath",
  "Jantjies",
  "Klaaste",
  "September",
  "October",
  "November",
  "Fortuin",
  "Boesak",
  "Appel",
  "Farao",
  "Davids",
  "Botha",
  "Van Der Merwe",
  "Van Zyl",
  "Nel",
  "Smit",
  "Venter",
  "Pretorius",
  "Coetzee",
  "Fourie",
  "Louw",
  "Van Niekerk",
  "Steyn",
  "Meyer",
  "Du Plessis",
  "Kruger",
  "Barnard",
  "Roux",
  "Joubert",
  "Cilliers",
  "De Villiers",
  "Boshoff",
  "Bezuidenhout",
  "Pienaar",
  "Viljoen",
  "Swanepoel",
  "Strydom",
  "Burger",
  "Oosthuizen",
  "Van Rooyen",
  "Potgieter",
  "Du Toit",
  "De Klerk",
  "Van Rensburg",
  "Van Wyk",
  "Olivier",
  "Haasbroek",
  "Bester",
  "Grobler",
  "Prinsloo",
  "Steenkamp",
  "Greyling",
  "Groenewald",
  "Van Heerden",
  "Visagie",
  "Swart",
  "Myburgh",
  "Engelbrecht",
  "Malan",
  "Van Jaarsveld",
  "Rossouw",
  "Theron",
  "Labuschagne",
  "Nienaber",
  "Jonker",
  "Claassen",
  "Vorster",
  "Els",
  "Spies",
  "Snyman",
  "Visser",
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzalez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Nelson",
  "Baker",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Evans",
  "Turner",
  "Diaz",
  "Parker",
  "Cruz",
  "Edwards",
  "Collins",
  "Reyes",
  "Stewart",
  "Morris",
  "Morales",
  "Murphy",
  "Cook",
  "Rogers",
  "Gutierrez",
  "Ortiz",
  "Morgan",
  "Cooper",
  "Peterson",
  "Bailey",
  "Reed",
  "Kelly",
  "Howard",
  "Ramos",
  "Kim",
  "Cox",
  "Ward",
  "Richardson",
  "Watson",
  "Brooks",
  "Chavez",
  "Wood",
  "James",
  "Bennett",
  "Gray",
  "Mendoza",
  "Ruiz",
  "Hughes",
  "Price",
  "Alvarez",
  "Castillo",
  "Sanders",
  "Myers",
  "Long",
  "Ross",
  "Foster",
  "Jimenez",
  "Powell",
  "Naik",
  "Maharaj",
  "Naicker",
  "Kirsten",
  "Pietersen",
  "Klaasen",
  "Van der Walt",
  "Nortje",
  "Coetzer",
  "Lombard",
  "Marais",
];

export const cities = [
  "Johannesburg",
  "Cape Town",
  "Durban",
  "Pretoria",
  "Port Elizabeth (Gqeberha)",
  "Bloemfontein",
  "East London",
  "Pietermaritzburg",
  "Kimberley",
  "Polokwane",
  "Nelspruit (Mbombela)",
  "Rustenburg",
  "Upington",
  "George",
  "Stellenbosch",
  "Somerset West",
  "Paarl",
  "Worcester",
  "Oudtshoorn",
  "Mossel Bay",
  "Knysna",
  "Plettenberg Bay",
  "Hermanus",
  "Malmesbury",
  "Saldanha",
  "Vredenburg",
  "Beaufort West",
  "Graaff-Reinet",
  "Cradock",
  "Grahamstown (Makhanda)",
  "Queenstown (Komani)",
  "King William's Town (Qonce)",
  "Uitenhage (Kariega)",
  "Pinetown",
  "Amanzimtoti",
  "Umhlanga",
  "Ballito",
  "Richards Bay",
  "Empangeni",
  "Newcastle",
  "Ladysmith",
  "Dundee",
  "Vryheid",
  "Margate",
  "Port Shepstone",
  "Kokstad",
  "Welkom",
  "Kroonstad",
  "Sasolburg",
  "Parys",
  "Bethlehem",
  "Harrismith",
  "Phuthaditjhaba",
  "Ficksburg",
  "Ladybrand",
  "Aliwal North",
  "De Aar",
  "Colesberg",
  "Springbok",
  "Calvinia",
  "Kuruman",
  "Kathu",
  "Vryburg",
  "Mahikeng",
  "Zeerust",
  "Lichtenburg",
  "Potchefstroom",
  "Klerksdorp",
  "Orkney",
  "Vanderbijlpark",
  "Vereeniging",
  "Meyerton",
  "Heidelberg",
  "Springs",
  "Brakpan",
  "Benoni",
  "Boksburg",
  "Kempton Park",
  "Germiston",
  "Alberton",
  "Roodepoort",
  "Randburg",
  "Sandton",
  "Midrand",
  "Centurion",
  "Akasia",
  "Mabopane",
  "Soshanguve",
  "Mamelodi",
  "Atteridgeville",
  "Tembisa",
  "Vosloorus",
  "Katlehong",
  "Thokoza",
  "Kagiso",
  "Mohlakeng",
  "Soweto",
  "Alexandra",
  "Diepsloot",
  "Ivory Park",
  "Orange Farm",
  "Sebokeng",
  "Evaton",
  "Sharpeville",
  "Boipatong",
  "Bophelong",
  "Duduza",
  "Tsakane",
  "KwaThema",
  "Daveyton",
  "Wattville",
  "Etwatwa",
  "Mhluzi",
  "Emalahleni (Witbank)",
  "Middelburg",
  "Secunda",
  "Bethal",
  "Ermelo",
  "Standerton",
  "Piet Retief (eMkhondo)",
  "Barberton",
  "White River",
  "Hazyview",
  "Graskop",
  "Sabie",
  "Lydenburg (Mashishing)",
  "Burgersfort",
  "Steelpoort",
  "Phalaborwa",
  "Tzaneen",
  "Giyani",
  "Makhado (Louis Trichardt)",
  "Musina",
  "Thohoyandou",
  "Malamulele",
  "Siyabuswa",
  "Dennilton",
  "Bela-Bela",
  "Modimolle",
  "Mookgophong",
  "Lephalale",
  "Thabazimbi",
  "Mokopane",
  "Stanger",
  "Tongaat",
  "Verulam",
  "Isipingo",
  "Kingsburgh",
  "Kloof",
  "Hillcrest",
  "Howick",
  "Estcourt",
  "Somerset East",
  "Queenstown",
  "Bisho",
  "Zwelitsha",
  "Mdantsane",
  "Caledon",
  "Swellendam",
  "Robertson",
  "Montagu",
  "Villiersdorp",
  "Ceres",
  "Tulbagh",
  "Wellington",
  "Franschhoek",
  "Laingsburg",
  "Prince Albert",
  "De Rust",
  "Riversdale",
  "Albertinia",
  "Groot-Brakrivier",
  "Virginia",
  "Odendaalsrus",
  "Hennenman",
  "Ventersburg",
  "Winburg",
  "Brandfort",
  "Theunissen",
  "Senekal",
  "Paul Roux",
  "Warden",
  "Villiers",
  "Frankfort",
  "Heilbron",
  "Koppies",
  "Mmabatho",
  "Coligny",
  "Ventersdorp",
  "Stilfontein",
  "Postmasburg",
  "Keimoes",
  "Kakamas",
  "Port Nolloth",
  "Alexander Bay",
  "Hanover",
  "Richmond",
  "Victoria West",
  "Carnarvon",
  "Williston",
  "Brandvlei",
  "Kenhardt",
  "Pofadder",
  "Aggeneys",
  "Prieska",
  "Douglas",
  "Barkly West",
  "Warrenton",
  "Christiana",
  "Bloemhof",
];

export const provinces = [
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "North West",
  "Northern Cape",
  "Western Cape",
];

export const streetNames = [
  "Mandela",
  "Tambo",
  "Sisulu",
  "Biko",
  "Luthuli",
  "Kerk",
  "Voortrekker",
  "Church",
  "Main",
  "Paul Kruger",
  "Vilakazi",
  "Mbeki",
  "Pretorius",
  "Smit",
  "Botha",
  "Oxford",
  "Adderley",
  "Long",
  "Bree",
  "Commissioner",
  "Rivonia",
  "Jan Smuts",
  "William Nicol",
  "Beyers Naude",
  "Hendrik Potgieter",
  "Sol Plaatje",
  "Chris Hani",
  "Walter Sisulu",
  "Pixley Ka Seme",
  "Anton Lembede",
  "Mahatma Gandhi",
  "Albert Luthuli",
  "Govan Mbeki",
  "Steve Biko",
  "Ruth First",
  "Helen Joseph",
  "Lilian Ngoyi",
  "Charlotte Maxeke",
  "Makabongwe",
  "Nyalunga",
  "Mzilikazi",
  "Shaka",
  "Cetshwayo",
  "Dingane",
  "Moshoeshoe",
  "Sekhukhune",
  "Mampuru",
  "Makhado",
  "Ramabulana",
  "Oak",
  "Pine",
  "Maple",
  "Cedar",
  "Elm",
  "Willow",
  "Ash",
  "Birch",
  "Walnut",
  "Chestnut",
  "Sycamore",
  "Magnolia",
  "Spruce",
  "Hickory",
  "Poplar",
  "Washington",
  "Lincoln",
  "Jefferson",
  "Madison",
  "Jackson",
  "Monroe",
  "Roosevelt",
  "Kennedy",
  "Clinton",
  "Bush",
  "Obama",
  "Park",
  "Broad",
  "High",
  "Water",
  "School",
  "Mill",
  "Spring",
  "Court",
  "River",
  "Lake",
  "Forest",
  "Hill",
  "Valley",
  "Meadow",
  "Nelson Mandela",
  "Oliver Tambo",
  "Thabo Mbeki",
  "Robert Sobukwe",
  "Pixley ka Isaka Seme",
  "Bram Fischer",
  "Andries",
  "Schoeman",
  "Skinner",
  "Van der Walt",
  "Esselen",
  "Jeppe",
  "Plein",
  "Strand",
  "Loop",
  "Buitengracht",
  "Buitenkant",
  "Roeland",
  "Darling",
  "Wale",
  "Keerom",
  "Burg",
  "St Georges",
  "Malibongwe",
  "Witkoppen",
  "Watermeyer",
  "Lynnwood",
  "Atterbury",
  "Menlyn",
  "Justice Mahomed",
  "Florence Ribeiro",
  "Leyds",
  "Burnett",
  "Duxbury",
  "Hay",
  "Hilda",
  "Florence Nightingale",
  "Louis Pasteur",
  "Alexander Fleming",
  "Marie Curie",
  "Albert Einstein",
  "Isaac Newton",
  "Galileo Galilei",
];

export const streetTypes = [
  "Street",
  "Road",
  "Avenue",
  "Drive",
  "Boulevard",
  "Way",
  "Close",
  "Lane",
  "Crescent",
  "Place",
  "Straat",
  "Weg",
  "Rylaan",
  "Singel",
  "Steeg",
  "Laan",
  "Court",
  "Terrace",
  "Square",
  "Plaza",
  "Alley",
  "Trail",
  "Parkway",
  "Circle",
  "Highway",
  "Expressway",
  "Freeway",
  "Turnpike",
  "Tollway",
  "Bypass",
  "Route",
  "Path",
  "Track",
  "Walk",
  "Promenade",
  "Esplanade",
  "Parade",
  "Mews",
  "Grove",
  "Gardens",
  "View",
  "Heights",
  "Hill",
  "Mount",
  "Ridge",
  "Valley",
  "Glen",
  "Dale",
  "Meadow",
  "Wood",
  "Forest",
  "Park",
  "Green",
  "Common",
  "Heath",
  "Moor",
  "Downs",
  "Fields",
  "Acres",
  "Estate",
  "Manor",
  "Farm",
  "Grange",
  "Lodge",
  "Cottage",
  "Villa",
  "House",
  "Hall",
];

export const suburbs = [
  "Sandton",
  "Rosebank",
  "Soweto",
  "Mamelodi",
  "Umlazi",
  "Khayelitsha",
  "Mitchells Plain",
  "Centurion",
  "Randburg",
  "Roodepoort",
  "Kempton Park",
  "Boksburg",
  "Benoni",
  "Germiston",
  "Alberton",
  "Edenvale",
  "Bedfordview",
  "Fourways",
  "Bryanston",
  "Midrand",
  "Sunnyside",
  "Arcadia",
  "Brooklyn",
  "Hatfield",
  "Lynnwood",
  "Menlyn",
  "Waterkloof",
  "Garsfontein",
  "Faerie Glen",
  "Moreleta Park",
  "Equestria",
  "Silver Lakes",
  "Atteridgeville",
  "Soshanguve",
  "Garankuwa",
  "Mabopane",
  "Winterveld",
  "Hammanskraal",
  "Temba",
  "Kagiso",
  "Mohlakeng",
  "Bekkersdal",
  "Khutsong",
  "Evaton",
  "Sebokeng",
  "Sharpeville",
  "Boipatong",
  "Bophelong",
  "Rietvallei",
  "Azaadville",
  "Lenasia",
  "Eldorado Park",
  "Ennerdale",
  "Orange Farm",
  "Diepsloot",
  "Ivory Park",
  "Rondebosch",
  "Claremont",
  "Newlands",
  "Kenilworth",
  "Wynberg",
  "Plumstead",
  "Diep River",
  "Heathfield",
  "Retreat",
  "Steenberg",
  "Tokai",
  "Kirstenhof",
  "Muizenberg",
  "St James",
  "Kalk Bay",
  "Fish Hoek",
  "Simon's Town",
  "Kommetjie",
  "Noordhoek",
  "Hout Bay",
  "Llandudno",
  "Camps Bay",
  "Clifton",
  "Bantry Bay",
  "Sea Point",
  "Green Point",
  "Mouille Point",
  "Waterfront",
  "Foreshore",
  "City Bowl",
  "Gardens",
  "Oranjezicht",
  "Tamboerskloof",
  "Vredehoek",
  "Bo-Kaap",
  "De Waterkant",
  "Zonnebloem",
  "Woodstock",
  "Observatory",
  "Mowbray",
  "Pinelands",
  "Thornton",
  "Maitland",
  "Kensington",
  "Factreton",
  "Goodwood",
  "Parow",
  "Bellville",
  "Durbanville",
  "Brackenfell",
  "Kraaifontein",
  "Kuils River",
  "Milnerton",
  "Table View",
  "Bloubergstrand",
  "Melkbosstrand",
  "Atlantis",
  "Gugulethu",
  "Nyanga",
  "Langa",
  "Crossroads",
  "Philippi",
  "Delft",
  "Belhar",
  "Bishop Lavis",
  "Elsies River",
  "Ravensmead",
  "Uitsig",
  "Valhalla Park",
  "Hanover Park",
  "Manenberg",
  "Heideveld",
  "Guguletu",
  "Athlone",
  "Crawford",
  "Lansdowne",
  "Rylands",
  "Gatesville",
  "Sybrand Park",
  "Hazendal",
  "Kewtown",
  "Bridgetown",
  "Silvertown",
  "Vanguard",
  "Welcome",
  "Surrey Estate",
  "Penlyn Estate",
  "Belgravia",
  "Charlesville",
  "Montana",
  "Montevideo",
  "Kalksteenfontein",
  "Bonteheuwel",
  "Berea",
  "Morningside",
  "Musgrave",
  "Glenwood",
  "Umbilo",
  "Congella",
  "Rossburgh",
  "Sea View",
  "Bellair",
  "Hillary",
  "Malvern",
  "Queensburgh",
  "Escombe",
  "Northdene",
  "Chatsworth",
  "Isipingo",
  "Amanzimtoti",
  "Kingsburgh",
  "Winkelspruit",
  "Illovo Beach",
  "Karridene",
  "Umkomaas",
  "Scottburgh",
  "Park Rynie",
  "Kelso",
  "Pennington",
  "Sezela",
  "Bazley",
  "Ifafa",
  "Mtwalume",
  "Hibberdene",
  "Umzumbe",
  "Pumula",
  "Melville",
  "Banana Beach",
  "Sunwich Port",
  "Southport",
  "Sea Park",
  "Umtentweni",
  "Port Shepstone",
  "Oslo Beach",
  "Shelly Beach",
  "St Michaels on Sea",
  "Uvongo",
  "Margate",
  "Ramsgate",
  "Southbroom",
  "Marina Beach",
  "Trafalgar",
  "Palm Beach",
  "Munster",
  "Glenmore",
  "Leisure Bay",
  "Port Edward",
  "Westville",
  "Pinetown",
  "New Germany",
  "Kloof",
  "Gillitts",
  "Hillcrest",
  "Botha's Hill",
  "Assagay",
  "Alverstone",
  "Waterfall",
  "Crestholme",
  "Forest Hills",
  "Winston Park",
  "Everton",
  "Wyebank",
  "Kwandengezi",
  "Clermont",
  "KwaDabeka",
  "Molweni",
  "Inanda",
  "Ntuzuma",
  "KwaMashu",
  "Phoenix",
  "Verulam",
  "Tongaat",
  "Umdloti",
  "La Mercy",
  "Westbrook",
  "Seatides",
  "Desainagar",
  "Genazzano",
  "Boy's Town",
  "Tongaat Beach",
  "Blythedale",
  "Zinkwazi",
  "Darnall",
  "Tugela Mouth",
  "Mandeni",
  "Sundumbili",
  "Amatikulu",
  "Gingindlovu",
  "Mtunzini",
  "Richards Bay",
  "Empangeni",
  "Mzingazi",
  "Meerensee",
  "Arboretum",
  "Veldenvlei",
  "Birdswood",
  "Brackenham",
  "Aquadene",
  "Ngwelezane",
  "Esikhaleni",
  "Vulindlela",
  "Felixton",
  "Kwambonambi",
];

export const emailDomains = [
  "gmail.com",
  "yahoo.com",
  "hotmail.com",
  "outlook.com",
  "icloud.com",
  "webmail.co.za",
  "telkomsa.net",
  "mweb.co.za",
  "vodamail.co.za",
  "mtn.co.za",
  "cellc.co.za",
  "protonmail.com",
  "me.com",
  "ymail.com",
  "zoho.com",
  "yandex.com",
  "mail.com",
  "gmx.com",
  "fastmail.com",
  "tutanota.com",
  "hey.com",
  "pm.me",
  "corporate.co.za",
  "business.co.za",
  "enterprise.co.za",
  "company.co.za",
  "firm.co.za",
  "agency.co.za",
  "group.co.za",
  "holding.co.za",
  "investments.co.za",
  "capital.co.za",
  "partners.co.za",
  "associates.co.za",
  "consulting.co.za",
  "solutions.co.za",
  "services.co.za",
  "systems.co.za",
  "technologies.co.za",
  "innovations.co.za",
  "creatives.co.za",
  "designs.co.za",
  "media.co.za",
  "communications.co.za",
  "marketing.co.za",
  "advertising.co.za",
  "pr.co.za",
  "events.co.za",
  "productions.co.za",
  "studios.co.za",
  "entertainment.co.za",
  "music.co.za",
  "records.co.za",
  "films.co.za",
  "pictures.co.za",
];

/** SA mobile network prefixes — all 10-digit numbers starting with 0XX */
export const mobileAreaCodes = [
  "060",
  "061",
  "062",
  "063",
  "064",
  "065",
  "066",
  "067",
  "071",
  "072",
  "073",
  "074",
  "076",
  "078",
  "079",
  "081",
  "082",
  "083",
  "084",
];

/** Realistic SA postal codes by area */
export const postalCodes = [
  // Gauteng
  "0001",
  "0002",
  "0081",
  "0082",
  "1459",
  "1461",
  "1545",
  "1600",
  "1601",
  "1619",
  "1627",
  "1628",
  "1632",
  "1700",
  "1709",
  "2000",
  "2001",
  "2090",
  "2092",
  "2094",
  "2095",
  "2107",
  "2109",
  "2128",
  "2129",
  "2131",
  "2132",
  "2135",
  "2136",
  "2137",
  "2138",
  "2139",
  "2140",
  "2141",
  "2142",
  "2143",
  "2144",
  "2145",
  "2146",
  "2147",
  "2148",
  "2149",
  "2150",
  "2151",
  "2152",
  "2153",
  "2154",
  "2155",
  "2156",
  "2157",
  "2190",
  "2191",
  "2192",
  "2193",
  "2194",
  "2195",
  "2196",
  // Western Cape
  "7000",
  "7001",
  "7100",
  "7101",
  "7130",
  "7200",
  "7300",
  "7400",
  "7405",
  "7410",
  "7415",
  "7441",
  "7500",
  "7530",
  "7550",
  "7570",
  "7580",
  "7600",
  "7700",
  "7750",
  "7800",
  // KwaZulu-Natal
  "3200",
  "3201",
  "3204",
  "3270",
  "3280",
  "3290",
  "3300",
  "3610",
  "3620",
  "3630",
  "4000",
  "4001",
  "4051",
  "4052",
  "4091",
  "4092",
  "4093",
  "4320",
  "4321",
  // Other provinces
  "0699",
  "0700",
  "0731",
  "1039",
  "1200",
  "1201",
  "5200",
  "5201",
  "5210",
  "5216",
  "6000",
  "6001",
  "8000",
  "8001",
  "9300",
  "9301",
];

export const companies = [
  "Shoprite",
  "Woolworths",
  "Pick n Pay",
  "Spar",
  "Checkers",
  "Makro",
  "Game",
  "Builders",
  "Clicks",
  "Dis-Chem",
  "Standard Bank",
  "Absa",
  "First National Bank",
  "Nedbank",
  "Capitec",
  "Investec",
  "Discovery",
  "Sanlam",
  "Old Mutual",
  "Vodacom",
  "MTN",
  "Telkom",
  "Cell C",
  "Rain",
  "MultiChoice",
  "Naspers",
  "Sasol",
  "Eskom",
  "Transnet",
  "Mondi",
  "Sappi",
  "Anglo American",
  "BHP",
  "Gold Fields",
  "Sibanye-Stillwater",
  "Harmony Gold",
  "Implats",
  "Tiger Brands",
  "Pioneer Foods",
  "AVI",
  "RCL Foods",
  "Astral Foods",
  "Bidvest",
  "Barloworld",
  "Imperial",
  "Motus",
  "WeBuyCars",
  "OUTsurance",
  "Hollard",
  "Momentum",
  "Liberty",
  "Clientèle",
  "Amazon Web Services",
  "Microsoft South Africa",
  "Oracle",
  "SAP",
  "Dimension Data",
  "Google",
  "Apple",
  "Microsoft",
  "Amazon",
  "Meta",
  "Tesla",
  "Nvidia",
  "Netflix",
  "Alphabet",
  "Intel",
  "IBM",
  "Cisco",
  "Qualcomm",
  "Adobe",
  "Salesforce",
  "HP",
  "Dell",
  "VMware",
  "ServiceNow",
  "Takealot",
  "Superbalist",
  "Mr Price",
  "Foschini Group",
  "Truworths",
  "Edcon",
  "Pepkor",
  "Massmart",
  "DionWired",
  "Incredible Connection",
  "HiFi Corp",
  "RSC",
  "JD Group",
  "Midas",
  "AutoZone",
  "Tiger Wheel & Tyre",
  "Kwik Fit",
  "Supa Quick",
  "Battery Centre",
  "PG Glass",
  "Glasfit",
  "Autoboys",
  "Mekor",
  "CFAO",
  "Unitrans",
  "Super Group",
  "Grindrod",
  "PRASA",
  "ACSA",
  "SAA",
  "Comair",
  "Kulula",
  "Mango",
  "FlySafair",
  "Airlink",
  "CemAir",
  "LIFT",
  "Uber",
  "Bolt",
  "DiDi",
  "InDrive",
  "Zomato",
  "Uber Eats",
  "Mr D Food",
  "Checkers Sixty60",
  "Pick n Pay ASAP",
  "Woolworths Dash",
  "Spar2U",
  "PnP Groceries",
  "OneCart",
  "Yebo Fresh",
  "Zulzi",
  "Bottles",
  "NetFlorist",
  "Bidorbuy",
  "Gumtree",
  "OLX",
  "Facebook Marketplace",
  "AutoTrader",
  "Cars.co.za",
  "Webuycars",
  "Weelee",
  "CarZar",
  "GetWorth",
  "CarGet",
  "CarKing",
  "CarMarket",
  "CarPrice",
  "CarValue",
  "CarTrade",
  "CarDeal",
];

export const jobTitles = [
  "Software Engineer",
  "Senior Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Architect",
  "Data Engineer",
  "Machine Learning Engineer",
  "Cybersecurity Analyst",
  "QA Engineer",
  "Mobile Developer",
  "Tech Lead",
  "Engineering Manager",
  "CTO",
  "Product Manager",
  "Senior Product Manager",
  "UX Designer",
  "UI Designer",
  "Product Designer",
  "UX Researcher",
  "Business Analyst",
  "Systems Analyst",
  "Data Analyst",
  "Data Scientist",
  "Business Intelligence Analyst",
  "Database Administrator",
  "Financial Analyst",
  "Accountant",
  "Chartered Accountant",
  "CFO",
  "Auditor",
  "Risk Manager",
  "Compliance Officer",
  "Actuarial Analyst",
  "Operations Manager",
  "Project Manager",
  "Programme Manager",
  "Scrum Master",
  "Agile Coach",
  "CEO",
  "COO",
  "General Manager",
  "Branch Manager",
  "Regional Manager",
  "Human Resources Manager",
  "Talent Acquisition Specialist",
  "Payroll Administrator",
  "Office Manager",
  "Executive Assistant",
  "Sales Manager",
  "Account Manager",
  "Marketing Manager",
  "Digital Marketing Specialist",
  "Content Creator",
  "Social Media Manager",
  "Brand Manager",
  "Legal Advisor",
  "Procurement Officer",
  "Supply Chain Manager",
  "Logistics Coordinator",
  "Customer Success Manager",
  "Technical Support Specialist",
  "Chief Executive Officer",
  "Chief Operating Officer",
  "Chief Financial Officer",
  "Chief Technology Officer",
  "Chief Marketing Officer",
  "Chief Information Officer",
  "Chief Data Officer",
  "Chief Product Officer",
  "Chief Human Resources Officer",
  "Chief Strategy Officer",
  "Chief Legal Officer",
  "Chief Security Officer",
  "Chief Risk Officer",
  "Chief Compliance Officer",
  "Chief Sustainability Officer",
  "Chief Diversity Officer",
  "Chief Revenue Officer",
  "Chief Customer Officer",
  "Chief Experience Officer",
  "Chief Design Officer",
  "Chief Innovation Officer",
  "Chief Transformation Officer",
  "Chief Digital Officer",
  "Chief Automation Officer",
  "Chief AI Officer",
  "Chief Cloud Officer",
  "Chief Architecture Officer",
  "Chief Engineering Officer",
  "Chief Infrastructure Officer",
  "Chief Network Officer",
  "Chief Systems Officer",
  "Chief Operations Officer",
  "Chief Service Officer",
  "Chief Support Officer",
  "Chief Success Officer",
  "Chief Quality Officer",
  "Chief Testing Officer",
  "Chief Release Officer",
  "Chief Deployment Officer",
  "Chief Delivery Officer",
  "Chief Implementation Officer",
  "Chief Integration Officer",
  "Chief Migration Officer",
  "Chief Upgrade Officer",
  "Chief Maintenance Officer",
  "Chief Reliability Officer",
  "Chief Availability Officer",
  "Chief Performance Officer",
  "Chief Optimization Officer",
  "Chief Scalability Officer",
  "Chief Resilience Officer",
  "Chief Continuity Officer",
  "Chief Disaster Recovery Officer",
  "Chief Backup Officer",
  "Chief Restore Officer",
  "Chief Storage Officer",
  "Chief Data Protection Officer",
  "Chief Privacy Officer",
  "Chief Governance Officer",
  "Chief Policy Officer",
  "Chief Audit Officer",
  "Chief Regulatory Officer",
  "Chief Legal Counsel",
  "General Counsel",
  "Senior Counsel",
  "Associate Counsel",
  "Corporate Counsel",
  "Legal Counsel",
  "Legal Consultant",
  "Legal Analyst",
  "Legal Assistant",
  "Paralegal",
  "Legal Secretary",
  "Legal Clerk",
  "Legal Intern",
  "Law Clerk",
  "Law Student",
  "Attorney",
  "Lawyer",
  "Solicitor",
  "Barrister",
  "Advocate",
  "Counselor",
  "Mediator",
  "Arbitrator",
  "Judge",
  "Magistrate",
  "Justice",
  "Clerk of Court",
  "Court Reporter",
  "Bailiff",
  "Sheriff",
  "Deputy",
  "Police Officer",
  "Detective",
  "Investigator",
  "Inspector",
  "Sergeant",
  "Lieutenant",
  "Captain",
  "Major",
  "Colonel",
  "General",
  "Admiral",
  "Commander",
  "Chief",
  "Director",
  "Commissioner",
  "Secretary",
  "Minister",
  "President",
  "Vice President",
  "Governor",
  "Mayor",
  "Council Member",
  "Senator",
  "Representative",
  "Member of Parliament",
  "Prime Minister",
  "Chancellor",
  "Premier",
  "Leader",
  "Head of State",
  "Head of Government",
  "Monarch",
  "King",
  "Queen",
  "Prince",
  "Princess",
  "Duke",
  "Duchess",
  "Marquis",
  "Marchioness",
  "Earl",
  "Countess",
  "Viscount",
  "Viscountess",
  "Baron",
  "Baroness",
  "Lord",
  "Lady",
  "Knight",
  "Dame",
  "Sir",
  "Madam",
  "Mr.",
  "Mrs.",
  "Ms.",
  "Miss",
  "Dr.",
  "Prof.",
  "Rev.",
  "Fr.",
  "Sr.",
  "Br.",
  "Rabbi",
  "Imam",
  "Sheikh",
  "Guru",
  "Master",
  "Sensei",
  "Sifu",
  "Coach",
  "Trainer",
  "Instructor",
  "Teacher",
  "Educator",
  "Professor",
  "Lecturer",
  "Tutor",
  "Mentor",
  "Guide",
  "Advisor",
  "Consultant",
  "Expert",
  "Specialist",
  "Professional",
  "Practitioner",
  "Technician",
  "Mechanic",
  "Engineer",
  "Architect",
  "Designer",
  "Developer",
  "Programmer",
  "Coder",
  "Hacker",
  "Creator",
  "Maker",
  "Builder",
  "Constructor",
  "Contractor",
  "Tradesperson",
  "Craftsperson",
  "Artisan",
  "Artist",
  "Musician",
  "Writer",
  "Author",
  "Poet",
  "Journalist",
  "Reporter",
  "Editor",
  "Publisher",
  "Broadcaster",
  "Presenter",
  "Host",
  "Anchor",
  "Actor",
  "Actress",
  "Performer",
  "Entertainer",
  "Comedian",
  "Dancer",
  "Singer",
  "Vocalist",
  "Instrumentalist",
  "Composer",
  "Arranger",
  "Producer",
  "Choreographer",
  "Stylist",
  "Makeup Artist",
  "Hair Stylist",
  "Wardrobe Consultant",
  "Costume Designer",
  "Set Designer",
  "Lighting Designer",
  "Sound Designer",
  "Audio Engineer",
  "Video Editor",
  "Animator",
  "Visual Effects Artist",
  "Graphic Designer",
  "Illustrator",
  "Photographer",
  "Videographer",
  "Cinematographer",
  "Camera Operator",
  "Grip",
  "Gaffer",
  "Best Boy",
  "Key Grip",
  "Dolly Grip",
  "Rigging Grip",
  "Construction Coordinator",
  "Prop Master",
  "Art Director",
  "Production Designer",
  "Location Manager",
  "Unit Production Manager",
  "Assistant Director",
  "Second Assistant Director",
  "Script Supervisor",
  "Continuity Editor",
  "Boom Operator",
  "Sound Mixer",
  "Foley Artist",
  "Dialogue Editor",
  "Sound Effects Editor",
  "Music Supervisor",
  "Conductor",
  "Orchestrator",
  "Copyist",
  "Music Editor",
  "Music Programmer",
  "Music Producer",
  "Recording Engineer",
  "Mixing Engineer",
  "Mastering Engineer",
  "Studio Manager",
  "A&R Representative",
  "Artist Manager",
  "Tour Manager",
  "Production Manager",
  "Stage Manager",
  "Lighting Director",
  "Sound Engineer",
  "Monitor Engineer",
  "Front of House Engineer",
  "Systems Engineer",
  "RF Technician",
  "Video Director",
  "Teleprompter Operator",
  "Graphics Operator",
  "Playback Operator",
  "Technical Director",
  "Executive Producer",
  "Showrunner",
  "Staff Writer",
  "Story Editor",
  "Executive Story Editor",
  "Co-Producer",
  "Supervising Producer",
  "Consulting Producer",
  "Line Producer",
  "Production Coordinator",
  "Production Assistant",
  "Runner",
  "Intern",
  "Apprentice",
  "Trainee",
  "Student",
  "Pupil",
  "Learner",
  "Scholar",
  "Fellow",
  "Researcher",
  "Scientist",
  "Analyst",
  "Observer",
  "Explorer",
  "Pioneer",
  "Innovator",
  "Inventor",
  "Discoverer",
  "Founder",
  "Co-Founder",
  "Owner",
  "Partner",
  "Principal",
  "Manager",
  "Supervisor",
  "Lead",
  "Head",
  "Executive",
  "Officer",
  "Administrator",
  "Coordinator",
  "Organizer",
  "Facilitator",
  "Moderator",
  "Negotiator",
  "Diplomat",
  "Ambassador",
  "Envoy",
  "Delegate",
  "Agent",
  "Broker",
  "Dealer",
  "Trader",
  "Merchant",
  "Vendor",
  "Seller",
  "Buyer",
  "Purchaser",
  "Consumer",
  "Customer",
  "Client",
  "Patron",
  "Guest",
  "Visitor",
  "Tourist",
  "Traveler",
  "Passenger",
  "Commuter",
  "Pedestrian",
  "Driver",
  "Pilot",
  "Navigator",
  "Operator",
  "Attendant",
  "Steward",
  "Hostess",
  "Waiter",
  "Waitress",
  "Server",
  "Bartender",
  "Barista",
  "Chef",
  "Cook",
  "Baker",
  "Butcher",
  "Fishmonger",
  "Greengrocer",
  "Grocer",
  "Shopkeeper",
  "Storekeeper",
  "Clerk",
  "Cashier",
  "Teller",
  "Receptionist",
  "Assistant",
  "Aide",
  "Helper",
  "Supporter",
  "Volunteer",
  "Donor",
  "Sponsor",
  "Benefactor",
  "Philanthropist",
  "Humanitarian",
  "Activist",
  "Campaigner",
  "Follower",
  "Member",
  "Participant",
  "Attendee",
  "Audience",
  "Spectator",
  "Fan",
  "Enthusiast",
  "Aficionado",
  "Connoisseur",
  "Authority",
  "Pundit",
  "Critic",
  "Reviewer",
  "Commentator",
  "Correspondent",
  "Columnist",
  "Blogger",
  "Vlogger",
  "Podcaster",
  "Streamer",
  "Influencer",
  "Planner",
  "Strategist",
  "Academic",
  "Intellectual",
  "Thinker",
  "Philosopher",
  "Theologian",
  "Historian",
  "Sociologist",
  "Psychologist",
  "Anthropologist",
  "Archaeologist",
  "Economist",
  "Political Scientist",
  "Geographer",
  "Demographer",
  "Statistician",
  "Mathematician",
  "Physicist",
  "Chemist",
  "Biologist",
  "Botanist",
  "Zoologist",
  "Ecologist",
  "Environmentalist",
  "Conservationist",
  "Astronomer",
  "Geologist",
  "Meteorologist",
  "Oceanographer",
  "Seismologist",
  "Volcanologist",
  "Paleontologist",
  "Linguist",
  "Philologist",
  "Etymologist",
  "Lexicographer",
  "Translator",
  "Interpreter",
  "Playwright",
  "Screenwriter",
  "Novelist",
  "Essayist",
  "Biographer",
];

export const departments = [
  "Engineering",
  "Product",
  "Design",
  "Data & Analytics",
  "Finance",
  "Human Resources",
  "Operations",
  "Marketing",
  "Sales",
  "Legal & Compliance",
  "Customer Success",
  "IT Infrastructure",
  "Supply Chain",
  "Research & Development",
  "Strategy",
  "Software Engineering",
  "Quality Assurance",
  "Information Technology",
  "Cloud Infrastructure",
  "DevOps",
  "Cybersecurity",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Business Intelligence",
  "Analytics",
  "Product Management",
  "User Experience (UX)",
  "User Interface (UI)",
  "Graphic Design",
  "Industrial Design",
  "Digital Marketing",
  "Content Marketing",
  "Social Media",
  "Public Relations",
  "Corporate Communications",
  "Business Development",
  "Account Management",
  "Customer Support",
  "Technical Support",
  "Talent Acquisition",
  "Learning & Development",
  "Employee Engagement",
  "Diversity & Inclusion",
  "Payroll",
  "Benefits",
  "Accounting",
  "Financial Planning & Analysis (FP&A)",
  "Treasury",
  "Tax",
  "Audit",
  "Legal",
  "Compliance",
  "Risk Management",
  "Corporate Governance",
  "Logistics",
  "Procurement",
  "Facilities Management",
  "Real Estate",
  "Innovation",
  "Corporate Development",
  "Mergers & Acquisitions",
  "Investor Relations",
  "Executive Office",
  "Administration",
];

// ── Word pool for text generation ─────────────────────────────────────────────

/** Common nouns — SA business, community, tech, and general */
export const loremNouns = [
  "system",
  "process",
  "solution",
  "platform",
  "service",
  "strategy",
  "approach",
  "framework",
  "model",
  "initiative",
  "project",
  "programme",
  "plan",
  "policy",
  "community",
  "township",
  "municipality",
  "province",
  "sector",
  "business",
  "enterprise",
  "organisation",
  "department",
  "team",
  "market",
  "economy",
  "development",
  "innovation",
  "technology",
  "network",
  "infrastructure",
  "application",
  "database",
  "resource",
  "opportunity",
  "challenge",
  "outcome",
  "impact",
  "partnership",
  "stakeholder",
  "access",
  "support",
  "capacity",
  "performance",
  "transformation",
  "empowerment",
  "growth",
  "delivery",
  "implementation",
  "compliance",
  "governance",
  "review",
  "report",
  "audit",
  "budget",
  "tender",
  "contract",
  "agreement",
  "tool",
  "workflow",
  "pipeline",
  "dashboard",
  "environment",
  "deployment",
  "release",
  "feature",
  "product",
  "prototype",
  "integration",
  "migration",
  "upgrade",
  "rollout",
  "update",
  "version",
  "patch",
  "fix",
  "test",
  "benchmark",
  "threshold",
  "target",
  "goal",
  "objective",
  "metric",
  "insight",
  "analysis",
  "research",
  "study",
  "survey",
  "feedback",
  "bursary",
  "clinic",
  "ward",
  "school",
  "campus",
  "graduate",
  "learner",
  "synergy",
  "paradigm",
  "KPI",
  "deliverable",
  "milestone",
  "roadmap",
  "lifecycle",
  "ecosystem",
  "architecture",
  "bandwidth",
  "scalability",
  "reliability",
  "availability",
  "optimization",
  "efficiency",
  "productivity",
  "profitability",
  "ROI",
  "TCO",
  "revenue",
  "margin",
  "expansion",
  "segment",
  "demographic",
  "audience",
  "customer",
  "client",
  "user",
  "consumer",
  "buyer",
  "shopper",
  "visitor",
  "guest",
  "member",
  "subscriber",
  "follower",
  "fan",
  "supporter",
  "advocate",
  "promoter",
  "influencer",
  "ambassador",
  "partner",
  "affiliate",
  "sponsor",
  "donor",
  "investor",
  "shareholder",
  "board",
  "committee",
  "council",
  "assembly",
  "forum",
  "panel",
  "symposium",
  "conference",
  "summit",
  "convention",
  "exhibition",
  "trade show",
  "fair",
  "festival",
  "carnival",
  "parade",
  "celebration",
  "event",
  "occasion",
  "function",
  "gathering",
  "meeting",
  "session",
  "workshop",
  "seminar",
  "webinar",
  "course",
  "class",
  "lesson",
  "tutorial",
  "lecture",
  "presentation",
  "speech",
  "talk",
  "address",
  "keynote",
  "briefing",
  "statement",
  "announcement",
  "press release",
  "newsletter",
  "bulletin",
  "journal",
  "magazine",
  "newspaper",
  "article",
  "blog post",
  "social media post",
  "tweet",
  "comment",
  "rating",
  "poll",
  "questionnaire",
  "interview",
  "focus group",
  "evaluation",
  "assessment",
  "inspection",
  "examination",
  "trial",
  "experiment",
  "pilot",
  "beta",
  "alpha",
  "launch",
  "resolution",
  "workaround",
  "enhancement",
  "functionality",
  "capability",
  "benefit",
  "value",
  "advantage",
  "edge",
  "competitiveness",
  "differentiation",
  "positioning",
  "branding",
  "identity",
  "image",
  "reputation",
  "perception",
  "awareness",
  "recognition",
  "loyalty",
  "trust",
  "confidence",
  "satisfaction",
  "delight",
  "happiness",
  "joy",
  "pleasure",
  "enjoyment",
  "fun",
  "entertainment",
  "amusement",
  "recreation",
  "leisure",
  "relaxation",
  "rest",
  "break",
  "holiday",
  "vacation",
  "trip",
  "journey",
  "tour",
  "expedition",
  "adventure",
  "quest",
  "mission",
  "aim",
  "purpose",
  "intent",
  "vision",
  "values",
  "principles",
  "beliefs",
  "culture",
  "ethos",
  "spirit",
  "vibe",
  "atmosphere",
  "mood",
  "feeling",
  "emotion",
  "sentiment",
  "attitude",
  "perspective",
  "viewpoint",
  "opinion",
  "belief",
  "thought",
  "idea",
  "concept",
  "notion",
  "theory",
  "hypothesis",
  "assumption",
  "premise",
  "argument",
  "point",
  "claim",
  "assertion",
  "fact",
  "truth",
  "reality",
  "actuality",
  "existence",
  "presence",
  "absence",
  "lack",
  "shortage",
  "scarcity",
  "deficiency",
  "weakness",
  "flaw",
  "defect",
  "error",
  "mistake",
  "fault",
  "failure",
  "breakdown",
  "crash",
  "outage",
  "downtime",
  "interruption",
  "disruption",
  "delay",
  "lag",
  "latency",
  "bottleneck",
  "constraint",
  "limitation",
  "restriction",
  "barrier",
  "obstacle",
  "hurdle",
  "difficulty",
  "problem",
  "issue",
  "trouble",
  "concern",
  "worry",
  "anxiety",
  "stress",
  "pressure",
  "tension",
  "conflict",
  "dispute",
  "disagreement",
  "controversy",
  "debate",
  "discussion",
  "conversation",
  "dialogue",
  "chat",
  "gossip",
  "rumor",
  "speculation",
  "guess",
  "estimate",
  "calculation",
  "computation",
  "measurement",
  "reading",
  "number",
  "figure",
  "statistic",
  "data",
  "information",
  "knowledge",
  "wisdom",
  "understanding",
  "comprehension",
  "consciousness",
  "mindfulness",
  "attention",
  "focus",
  "concentration",
  "distraction",
  "disturbance",
  "noise",
  "interference",
  "static",
  "echo",
  "reverb",
  "resonance",
  "vibration",
  "frequency",
  "wave",
  "signal",
  "pulse",
  "beat",
  "rhythm",
  "tempo",
  "pace",
  "speed",
  "velocity",
  "acceleration",
  "momentum",
  "inertia",
  "force",
  "power",
  "energy",
  "strength",
  "might",
  "potency",
  "ability",
  "skill",
  "talent",
  "gift",
  "knack",
  "flair",
  "genius",
  "brilliance",
  "intelligence",
  "smartness",
  "cleverness",
  "shrewdness",
  "cunning",
  "craftiness",
  "slyness",
  "trickery",
  "deception",
  "fraud",
  "scam",
  "hoax",
  "fake",
  "forgery",
  "counterfeit",
  "copy",
  "replica",
  "clone",
  "duplicate",
  "imitation",
  "mock-up",
  "simulation",
  "pattern",
  "template",
  "design",
  "layout",
  "structure",
  "format",
  "arrangement",
  "organization",
  "method",
  "procedure",
  "practice",
  "routine",
  "habit",
  "custom",
  "tradition",
  "ritual",
  "ceremony",
  "observance",
  "anniversary",
  "birthday",
  "wedding",
  "funeral",
  "graduation",
  "prom",
  "dance",
  "party",
  "sermon",
  "homily",
  "eulogy",
  "toast",
  "tribute",
  "salute",
  "cheer",
  "applause",
  "ovation",
  "boo",
  "hiss",
  "jeer",
  "taunt",
  "insult",
  "slur",
  "curse",
  "swear",
  "profanity",
  "obscenity",
  "vulgarity",
  "indecency",
  "impropriety",
  "misconduct",
  "misbehavior",
  "wrongdoing",
  "crime",
  "offense",
  "felony",
  "misdemeanor",
  "infraction",
  "violation",
  "breach",
  "transgression",
  "sin",
  "vice",
  "evil",
  "wickedness",
  "corruption",
  "depravity",
  "immorality",
  "unethicality",
  "dishonesty",
  "deceit",
];

/** Common adjectives — SA English formal and informal */
export const loremAdjectives = [
  "sustainable",
  "innovative",
  "critical",
  "robust",
  "effective",
  "comprehensive",
  "integrated",
  "dynamic",
  "strategic",
  "inclusive",
  "diverse",
  "local",
  "national",
  "digital",
  "rural",
  "urban",
  "modern",
  "traditional",
  "essential",
  "fundamental",
  "significant",
  "positive",
  "meaningful",
  "impactful",
  "collaborative",
  "responsive",
  "transparent",
  "accountable",
  "viable",
  "scalable",
  "flexible",
  "reliable",
  "secure",
  "advanced",
  "specialised",
  "dedicated",
  "qualified",
  "experienced",
  "skilled",
  "capable",
  "competitive",
  "successful",
  "operational",
  "functional",
  "technical",
  "financial",
  "commercial",
  "public",
  "private",
  "provincial",
  "municipal",
  "proactive",
  "agile",
  "resilient",
  "streamlined",
  "automated",
  "optimised",
  "unified",
  "distributed",
  "cloud-based",
  "open-source",
  "real-time",
  "data-driven",
  "user-friendly",
  "disruptive",
  "cutting-edge",
  "bleeding-edge",
  "next-generation",
  "state-of-the-art",
  "world-class",
  "best-in-class",
  "industry-leading",
  "market-leading",
  "award-winning",
  "top-tier",
  "premium",
  "exclusive",
  "elite",
  "luxury",
  "high-end",
  "boutique",
  "custom",
  "bespoke",
  "tailored",
  "personalized",
  "individualized",
  "unique",
  "distinctive",
  "original",
  "creative",
  "imaginative",
  "visionary",
  "forward-thinking",
  "progressive",
  "contemporary",
  "current",
  "up-to-date",
  "latest",
  "newest",
  "fresh",
  "novel",
  "groundbreaking",
  "revolutionary",
  "transformative",
  "game-changing",
  "paradigm-shifting",
  "radical",
  "extreme",
  "drastic",
  "severe",
  "intense",
  "fierce",
  "aggressive",
  "cutthroat",
  "ruthless",
  "merciless",
  "relentless",
  "unstoppable",
  "invincible",
  "unbeatable",
  "undefeated",
  "champion",
  "victorious",
  "triumphant",
  "prosperous",
  "thriving",
  "flourishing",
  "booming",
  "growing",
  "expanding",
  "scaling",
  "soaring",
  "skyrocketing",
  "exploding",
  "bursting",
  "overflowing",
  "abundant",
  "plentiful",
  "copious",
  "profuse",
  "bountiful",
  "generous",
  "liberal",
  "lavish",
  "extravagant",
  "luxurious",
  "opulent",
  "sumptuous",
  "magnificent",
  "grand",
  "majestic",
  "splendid",
  "glorious",
  "fabulous",
  "fantastic",
  "marvelous",
  "wonderful",
  "amazing",
  "astonishing",
  "astounding",
  "incredible",
  "unbelievable",
  "mind-blowing",
  "breathtaking",
  "stunning",
  "striking",
  "arresting",
  "captivating",
  "fascinating",
  "compelling",
  "engaging",
  "absorbing",
  "enthralling",
  "spellbinding",
  "hypnotic",
  "mesmerizing",
  "enchanting",
  "charming",
  "delightful",
  "pleasing",
  "appealing",
  "attractive",
  "alluring",
  "tempting",
  "enticing",
  "seductive",
  "irresistible",
  "magnetic",
  "charismatic",
  "energetic",
  "vigorous",
  "sturdy",
  "strong",
  "powerful",
  "mighty",
  "potent",
  "forceful",
  "influential",
  "persuasive",
  "convincing",
  "cogent",
  "sound",
  "valid",
  "logical",
  "rational",
  "reasonable",
  "sensible",
  "practical",
  "pragmatic",
  "realistic",
  "down-to-earth",
  "grounded",
  "level-headed",
  "balanced",
  "even-tempered",
  "calm",
  "cool",
  "collected",
  "composed",
  "unruffled",
  "unflappable",
  "serene",
  "tranquil",
  "peaceful",
  "quiet",
  "still",
  "silent",
  "hushed",
  "muted",
  "subdued",
  "understated",
  "subtle",
  "nuanced",
  "delicate",
  "refined",
  "elegant",
  "graceful",
  "sophisticated",
  "polished",
  "sleek",
  "smooth",
  "seamless",
  "flawless",
  "perfect",
  "impeccable",
  "spotless",
  "stainless",
  "pristine",
  "pure",
  "unblemished",
  "untarnished",
  "unsullied",
  "unspoiled",
  "untouched",
  "virgin",
  "new",
  "raw",
  "unprocessed",
  "unrefined",
  "crude",
  "coarse",
  "rough",
  "harsh",
  "abrasive",
  "grating",
  "jarring",
  "discordant",
  "dissonant",
  "cacophonous",
  "loud",
  "noisy",
  "deafening",
  "thundering",
  "roaring",
  "howling",
  "screaming",
  "shrieking",
  "piercing",
  "shrill",
  "high-pitched",
  "squeaky",
  "creaky",
  "scratchy",
  "raspy",
  "hoarse",
  "husky",
  "gruff",
  "gravelly",
  "deep",
  "low",
  "bass",
  "baritone",
  "tenor",
  "alto",
  "soprano",
  "vocal",
  "instrumental",
  "musical",
  "melodic",
  "harmonic",
  "rhythmic",
  "syncopated",
  "upbeat",
  "downbeat",
  "fast",
  "slow",
  "moderate",
  "brisk",
  "rapid",
  "swift",
  "quick",
  "speedy",
  "hasty",
  "hurried",
  "rushed",
  "frantic",
  "frenetic",
  "hectic",
  "chaotic",
  "disorganized",
  "messy",
  "untidy",
  "sloppy",
  "careless",
  "negligent",
  "reckless",
  "rash",
  "impulsive",
  "spontaneous",
  "unplanned",
  "unpremeditated",
  "extemporaneous",
  "impromptu",
  "ad-lib",
  "off-the-cuff",
  "unscripted",
  "unrehearsed",
  "natural",
  "authentic",
  "genuine",
  "real",
  "true",
  "factual",
  "accurate",
  "correct",
  "right",
  "proper",
  "appropriate",
  "fitting",
  "suitable",
  "apt",
  "relevant",
  "pertinent",
  "applicable",
  "germane",
  "related",
  "connected",
  "associated",
  "linked",
  "tied",
  "bound",
  "attached",
  "joined",
  "united",
  "combined",
  "merged",
  "incorporated",
  "assimilated",
  "absorbed",
  "digested",
  "understood",
  "comprehended",
  "grasped",
  "realized",
  "recognized",
  "acknowledged",
  "accepted",
  "admitted",
  "confessed",
  "revealed",
  "disclosed",
  "uncovered",
  "exposed",
  "unveiled",
  "unmasked",
  "bared",
  "naked",
  "nude",
  "stripped",
  "denuded",
  "divested",
  "deprived",
  "bereft",
  "destitute",
  "poor",
  "impoverished",
  "needy",
  "indigent",
  "penniless",
  "broke",
  "bankrupt",
  "insolvent",
  "ruined",
  "destroyed",
  "devastated",
  "demolished",
  "wrecked",
  "smashed",
  "shattered",
  "broken",
  "fractured",
  "cracked",
  "split",
  "torn",
  "ripped",
  "shredded",
  "frayed",
  "worn",
  "tattered",
  "ragged",
  "shabby",
  "dilapidated",
  "derelict",
  "abandoned",
  "deserted",
  "empty",
  "vacant",
  "bare",
  "blank",
  "void",
  "null",
  "invalid",
  "worthless",
  "useless",
  "futile",
  "vain",
  "fruitless",
  "unproductive",
  "barren",
  "sterile",
  "infertile",
  "impotent",
  "powerless",
  "weak",
  "feeble",
  "frail",
  "fragile",
  "brittle",
  "crisp",
  "crunchy",
  "chewy",
  "soft",
  "mushy",
  "squishy",
  "spongy",
  "springy",
  "bouncy",
  "elastic",
  "pliable",
  "supple",
  "yielding",
  "compliant",
  "obedient",
  "submissive",
  "docile",
  "tame",
  "domesticated",
  "wild",
  "feral",
  "savage",
  "vicious",
  "cruel",
  "brutal",
  "barbaric",
  "inhuman",
  "monstrous",
  "hideous",
  "ugly",
  "repulsive",
  "revolting",
  "disgusting",
  "sickening",
  "nauseating",
  "appalling",
  "horrifying",
  "terrifying",
  "frightening",
  "scary",
  "creepy",
  "spooky",
  "eerie",
  "weird",
  "strange",
  "odd",
  "peculiar",
  "bizarre",
  "eccentric",
  "quirky",
  "unconventional",
  "unorthodox",
  "heterodox",
  "heretical",
  "blasphemous",
  "sacrilegious",
  "profane",
  "secular",
  "worldly",
  "earthly",
  "mundane",
  "ordinary",
  "common",
  "average",
  "normal",
  "typical",
  "standard",
  "regular",
  "routine",
  "everyday",
  "daily",
  "weekly",
  "monthly",
  "yearly",
  "annual",
  "perennial",
  "eternal",
  "everlasting",
  "immortal",
  "infinite",
  "boundless",
  "limitless",
  "endless",
  "ceaseless",
  "incessant",
  "continuous",
  "constant",
  "perpetual",
  "permanent",
  "lasting",
  "enduring",
  "abiding",
  "stable",
  "steady",
  "firm",
  "solid",
  "hard",
  "tough",
  "rigid",
  "stiff",
  "inflexible",
  "unyielding",
  "unbending",
  "uncompromising",
  "stubborn",
  "obstinate",
  "headstrong",
  "willful",
  "determined",
  "resolute",
  "steadfast",
  "unwavering",
  "unfaltering",
  "unflinching",
  "fearless",
  "brave",
  "courageous",
  "valiant",
  "heroic",
  "gallant",
  "chivalrous",
  "noble",
  "honorable",
  "upright",
  "righteous",
  "virtuous",
  "moral",
  "ethical",
  "principled",
  "scrupulous",
  "conscientious",
  "meticulous",
  "fastidious",
  "exacting",
  "demanding",
  "strict",
  "stern",
  "punishing",
  "grueling",
  "exhausting",
  "tiring",
  "fatiguing",
  "wearisome",
  "tedious",
  "boring",
  "dull",
  "uninteresting",
  "monotonous",
  "repetitive",
  "predictable",
  "expected",
  "anticipated",
  "foreseen",
  "known",
  "familiar",
  "recognizable",
  "identifiable",
  "distinguishable",
  "noticeable",
  "obvious",
  "evident",
  "apparent",
  "clear",
  "plain",
  "simple",
  "easy",
  "effortless",
  "facile",
  "fluid",
  "flowing",
  "cultured",
  "civilized",
  "polite",
  "courteous",
  "respectful",
  "deferential",
  "reverent",
  "devout",
  "pious",
  "religious",
  "spiritual",
  "holy",
  "sacred",
  "divine",
  "heavenly",
  "celestial",
  "angelic",
  "seraphic",
  "cherubic",
  "innocent",
  "chaste",
  "virginal",
  "modest",
  "humble",
  "meek",
  "mild",
  "gentle",
  "tender",
  "kind",
  "compassionate",
  "sympathetic",
  "empathetic",
  "understanding",
  "forgiving",
  "merciful",
  "lenient",
  "tolerant",
  "broad-minded",
  "open-minded",
  "receptive",
  "amenable",
  "agreeable",
  "pleasant",
  "friendly",
  "amiable",
  "affable",
  "genial",
  "sociable",
  "outgoing",
  "extroverted",
  "gregarious",
  "talkative",
  "chatty",
  "loquacious",
  "garrulous",
  "voluble",
  "articulate",
  "eloquent",
  "fluent",
  "expressive",
  "communicative",
  "informative",
  "educational",
  "instructive",
  "enlightening",
  "illuminating",
  "revealing",
  "telling",
  "important",
  "crucial",
  "vital",
  "indispensable",
  "necessary",
  "required",
  "mandatory",
  "compulsory",
  "obligatory",
  "binding",
  "irrevocable",
  "irreversible",
  "final",
  "ultimate",
  "absolute",
  "total",
  "complete",
  "exhaustive",
  "thorough",
  "detailed",
  "minute",
  "precise",
  "exact",
  "legitimate",
];

/** Common verbs (base form, also used for varied inflections) */
export const loremVerbs = [
  "provide",
  "support",
  "enable",
  "facilitate",
  "ensure",
  "deliver",
  "develop",
  "implement",
  "transform",
  "address",
  "manage",
  "strengthen",
  "improve",
  "enhance",
  "build",
  "create",
  "establish",
  "promote",
  "drive",
  "accelerate",
  "deploy",
  "launch",
  "achieve",
  "complete",
  "expand",
  "coordinate",
  "align",
  "integrate",
  "optimise",
  "streamline",
  "monitor",
  "analyse",
  "evaluate",
  "assess",
  "identify",
  "resolve",
  "mitigate",
  "reduce",
  "increase",
  "maintain",
  "synthesize",
  "synergize",
  "leverage",
  "optimize",
  "maximize",
  "minimize",
  "automate",
  "release",
  "ship",
  "execute",
  "install",
  "configure",
  "setup",
  "initialize",
  "boot",
  "restart",
  "reboot",
  "shutdown",
  "close",
  "open",
  "start",
  "stop",
  "pause",
  "resume",
  "play",
  "record",
  "save",
  "load",
  "import",
  "export",
  "upload",
  "download",
  "sync",
  "backup",
  "restore",
  "recover",
  "repair",
  "fix",
  "patch",
  "update",
  "upgrade",
  "migrate",
  "transfer",
  "move",
  "copy",
  "paste",
  "cut",
  "delete",
  "remove",
  "destroy",
  "erase",
  "wipe",
  "clean",
  "clear",
  "format",
  "partition",
  "allocate",
  "assign",
  "delegate",
  "distribute",
  "share",
  "publish",
  "broadcast",
  "transmit",
  "receive",
  "send",
  "forward",
  "reply",
  "answer",
  "respond",
  "react",
  "interact",
  "engage",
  "communicate",
  "collaborate",
  "cooperate",
  "participate",
  "join",
  "leave",
  "quit",
  "exit",
  "enter",
  "login",
  "logout",
  "register",
  "signup",
  "subscribe",
  "unsubscribe",
  "follow",
  "unfollow",
  "like",
  "dislike",
  "upvote",
  "downvote",
  "rate",
  "review",
  "comment",
  "post",
  "tweet",
  "pin",
  "tag",
  "mention",
  "message",
  "chat",
  "call",
  "video",
  "stream",
  "watch",
  "view",
  "read",
  "write",
  "edit",
  "design",
  "construct",
  "assemble",
  "manufacture",
  "produce",
  "generate",
  "fabricate",
  "invent",
  "discover",
  "explore",
  "research",
  "investigate",
  "analyze",
  "measure",
  "test",
  "verify",
  "validate",
  "certify",
  "approve",
  "reject",
  "deny",
  "refuse",
  "accept",
  "agree",
  "disagree",
  "argue",
  "debate",
  "discuss",
  "negotiate",
  "compromise",
  "settle",
  "solve",
  "mend",
  "heal",
  "cure",
  "treat",
  "care",
  "help",
  "assist",
  "aid",
  "guide",
  "lead",
  "direct",
  "supervise",
  "oversee",
  "control",
  "regulate",
  "govern",
  "rule",
  "command",
  "order",
  "instruct",
  "teach",
  "educate",
  "train",
  "coach",
  "mentor",
  "advise",
  "consult",
  "counsel",
  "recommend",
  "suggest",
  "propose",
  "pitch",
  "present",
  "show",
  "demonstrate",
  "display",
  "exhibit",
  "reveal",
  "disclose",
  "uncover",
  "expose",
  "unveil",
  "unmask",
  "hide",
  "conceal",
  "cover",
  "mask",
  "camouflage",
  "disguise",
  "obscure",
  "blur",
  "fade",
  "disappear",
  "vanish",
  "evaporate",
  "dissolve",
  "melt",
  "freeze",
  "solidify",
  "harden",
  "soften",
  "liquefy",
  "vaporize",
  "condense",
  "compress",
  "stretch",
  "shrink",
  "contract",
  "grow",
  "evolve",
  "mature",
  "age",
  "die",
  "perish",
  "expire",
  "decay",
  "rot",
  "decompose",
  "disintegrate",
  "crumble",
  "collapse",
  "fall",
  "drop",
  "sink",
  "plunge",
  "dive",
  "crash",
  "smash",
  "break",
  "shatter",
  "crack",
  "split",
  "tear",
  "rip",
  "shred",
  "slice",
  "chop",
  "dice",
  "mince",
  "grate",
  "peel",
  "skin",
  "shell",
  "husk",
  "core",
  "seed",
  "pit",
  "bone",
  "fillet",
  "carve",
  "roast",
  "bake",
  "broil",
  "grill",
  "fry",
  "saute",
  "boil",
  "simmer",
  "stew",
  "steam",
  "poach",
  "blanch",
  "scald",
  "scorch",
  "burn",
  "char",
  "toast",
  "warm",
  "heat",
  "cool",
  "chill",
  "thaw",
  "mix",
  "blend",
  "stir",
  "whisk",
  "beat",
  "whip",
  "fold",
  "knead",
  "roll",
  "press",
  "squeeze",
  "crush",
  "mash",
  "puree",
  "strain",
  "filter",
  "sift",
  "pour",
  "spill",
  "splash",
  "sprinkle",
  "scatter",
  "spread",
  "smear",
  "daub",
  "paint",
  "draw",
  "sketch",
  "trace",
  "outline",
  "color",
  "shade",
  "tint",
  "dye",
  "stain",
  "bleach",
  "wash",
  "scrub",
  "scour",
  "dust",
  "sweep",
  "mop",
  "vacuum",
  "polish",
  "shine",
  "wax",
  "buff",
  "rub",
  "massage",
  "stroke",
  "pet",
  "pat",
  "tap",
  "knock",
  "hit",
  "strike",
  "punch",
  "slap",
  "smack",
  "spank",
  "kick",
  "bite",
  "chew",
  "swallow",
  "digest",
  "absorb",
  "assimilate",
  "incorporate",
  "merge",
  "combine",
  "unite",
  "connect",
  "link",
  "attach",
  "fasten",
  "tie",
  "bind",
  "secure",
  "lock",
  "unlock",
  "shut",
  "seal",
  "pack",
  "unpack",
  "unload",
  "fill",
  "empty",
  "drain",
  "pump",
  "siphon",
  "suck",
  "blow",
  "puff",
  "pant",
  "gasp",
  "breathe",
  "inhale",
  "exhale",
  "sigh",
  "yawn",
  "cough",
  "sneeze",
  "hiccup",
  "burp",
  "belch",
  "fart",
  "spit",
  "drool",
  "sweat",
  "perspire",
  "bleed",
  "cry",
  "weep",
  "sob",
  "wail",
  "howl",
  "scream",
  "shriek",
  "yell",
  "shout",
  "sing",
  "hum",
  "whistle",
  "whisper",
  "mutter",
  "mumble",
  "grumble",
  "growl",
  "snarl",
  "bark",
  "meow",
  "purr",
  "moo",
  "baa",
  "oink",
  "cluck",
  "quack",
  "chirp",
  "squawk",
  "roar",
  "bellow",
  "trumpet",
  "neigh",
  "whinny",
  "snort",
  "bray",
  "hoot",
  "screech",
];

/** Connectors and filler words for natural-looking text */
export const loremFillers = [
  "and",
  "but",
  "while",
  "as well as",
  "alongside",
  "however",
  "therefore",
  "thus",
  "furthermore",
  "additionally",
  "consequently",
  "particularly",
  "especially",
  "significantly",
  "effectively",
  "successfully",
  "consistently",
  "progressively",
  "increasingly",
  "collectively",
  "nationally",
  "locally",
  "in order to",
  "so that",
  "which means",
  "resulting in",
  "based on",
  "in line with",
  "in response to",
  "due to",
  "moreover",
  "nevertheless",
  "nonetheless",
  "notwithstanding",
  "conversely",
  "meanwhile",
  "subsequently",
  "eventually",
  "ultimately",
  "finally",
  "initially",
  "primarily",
  "principally",
  "chiefly",
  "mainly",
  "mostly",
  "largely",
  "predominantly",
  "generally",
  "typically",
  "usually",
  "normally",
  "regularly",
  "frequently",
  "often",
  "sometimes",
  "occasionally",
  "rarely",
  "seldom",
  "hardly",
  "scarcely",
  "barely",
  "almost",
  "nearly",
  "virtually",
  "practically",
  "essentially",
  "fundamentally",
  "basically",
  "literally",
  "truly",
  "really",
  "actually",
  "in fact",
  "indeed",
  "certainly",
  "surely",
  "definitely",
  "absolutely",
  "positively",
  "undeniably",
  "unquestionably",
  "without a doubt",
  "of course",
  "naturally",
  "obviously",
  "evidently",
  "apparently",
  "seemingly",
  "supposedly",
  "allegedly",
  "presumably",
  "arguably",
  "conceivably",
  "possibly",
  "perhaps",
  "maybe",
  "probably",
  "likely",
  "unlikely",
  "hopefully",
  "thankfully",
  "fortunately",
  "unfortunately",
  "sadly",
  "regrettably",
  "alas",
  "surprisingly",
  "astonishingly",
  "amazingly",
  "incredibly",
  "unbelievably",
  "ironically",
  "paradoxically",
  "funnily enough",
  "strangely",
  "oddly",
  "curiously",
  "interestingly",
  "fascinatingly",
  "importantly",
  "crucially",
  "vitally",
  "critically",
  "notably",
  "specifically",
  "namely",
  "for example",
  "for instance",
  "such as",
  "including",
  "like",
  "along with",
  "together with",
  "coupled with",
  "combined with",
  "in addition to",
  "besides",
  "apart from",
  "aside from",
  "except for",
  "excluding",
  "other than",
  "instead of",
  "rather than",
  "in place of",
  "as opposed to",
  "unlike",
  "contrary to",
  "in contrast to",
  "compared to",
  "relative to",
  "in relation to",
  "with regard to",
  "with respect to",
  "concerning",
  "regarding",
  "about",
  "on the subject of",
  "in connection with",
  "associated with",
  "related to",
  "pertaining to",
  "in terms of",
  "from the perspective of",
  "from the point of view of",
  "in the context of",
  "in light of",
  "given",
  "considering",
  "taking into account",
  "bearing in mind",
  "keeping in mind",
  "assuming",
  "presuming",
  "supposing",
  "provided that",
  "on the condition that",
  "as long as",
  "so long as",
  "if",
  "unless",
  "even if",
  "whether",
  "or not",
  "in case",
  "just in case",
  "in the event that",
  "should",
  "would",
  "could",
  "might",
  "may",
  "can",
  "will",
  "shall",
  "must",
  "ought to",
  "have to",
  "need to",
  "be able to",
  "be going to",
  "be about to",
  "be likely to",
  "be supposed to",
  "be expected to",
  "be meant to",
  "be bound to",
  "be sure to",
  "be certain to",
  "be destined to",
  "be fated to",
  "be doomed to",
];

/** Pre-built realistic article/post title fragments */
export const titlePhrases = [
  "Building Scalable Systems",
  "Introduction to Cloud-Native Architecture",
  "Understanding Database Performance",
  "A Guide to API Design",
  "Improving Team Productivity",
  "Digital Transformation in Africa",
  "Security Best Practices",
  "DevOps for Growing Teams",
  "Data-Driven Decision Making",
  "The Future of Remote Work",
  "Managing Technical Debt",
  "Microservices vs Monolith",
  "Testing Strategies for Modern Apps",
  "Building Inclusive Products",
  "Performance Optimisation Techniques",
  "Infrastructure as Code",
  "Observability and Monitoring",
  "Sustainable Software Development",
  "Community-Driven Innovation",
  "Access to Technology in Rural Areas",
  "Mobile-First Development",
  "Open Source in the Enterprise",
  "From MVP to Production",
  "Continuous Delivery Pipelines",
  "Lessons from Scaling Startups",
  "The Cost of Poor Architecture",
  "Mentorship in the Tech Industry",
  "Women in Technology South Africa",
  "Agile Beyond the Buzzword",
  "How to Run Effective Retrospectives",
  "Designing for Low-Bandwidth Users",
  "Localisation and Internationalisation",
  "Building with TypeScript",
  "Real-Time Data Streaming",
  "Machine Learning in Production",
  "The Art of Code Review",
  "Documentation That Developers Actually Read",
  "Debugging Production Issues",
  "Zero-Downtime Deployments",
  "Kubernetes for Small Teams",
  "Advanced Patterns in React",
  "Mastering State Management",
  "Server-Side Rendering Explained",
  "Static Site Generation vs SSR",
  "The Ultimate Guide to Next.js",
  "Building Resilient Microservices",
  "Event-Driven Architecture Deep Dive",
  "GraphQL best practices",
  "REST vs GraphQL",
  "Building a Design System",
  "Component-Driven UI",
  "Automated Testing for Frontends",
  "E2E Testing with Cypress",
  "Unit Testing with Jest",
  "Mocking APIs for Tests",
  "Test-Driven Development (TDD) Guide",
  "CI/CD Pipelines with GitHub Actions",
  "Deploying Node.js Apps",
  "Containerization with Docker",
  "Kubernetes for Beginners",
  "Scaling Node.js Applications",
  "Performance Tuning in V8",
  "Memory Management in JavaScript",
  "Asynchronous Programming Patterns",
  "Promises vs Async/Await",
  "RxJS and Reactive Programming",
  "Functional Programming in TypeScript",
  "Object-Oriented Design Principles",
  "SOLID Principles Explained",
  "Design Patterns in Practice",
  "Refactoring Legacy Code",
  "Code Smells and How to Fix Them",
  "Writing Clean Code",
  "The Pragmatic Programmer's Guide",
  "Agile Methodologies in Software",
  "Scrum vs Kanban",
  "Effective Code Reviews",
  "Pair Programming Benefits",
  "Remote Team Collaboration",
  "Open Source Contribution Guide",
  "Monorepo Management with Turborepo",
  "Microfrontends Architecture",
  "WebAssembly and the Future",
  "Serverless Computing Concepts",
  "AWS Lambda Deep Dive",
  "Cloud Functions vs Lambda",
  "Database Indexing Strategies",
  "SQL vs NoSQL",
  "PostgreSQL Advanced Features",
  "MongoDB Aggregation Pipeline",
  "Redis Caching Strategies",
  "Elasticsearch Full-Text Search",
  "Message Queues with RabbitMQ",
  "Kafka Event Streaming",
  "WebSockets for Real-Time Apps",
  "Progressive Web Apps (PWA)",
  "Offline-First Development",
  "Web Accessibility (A11y) Guide",
  "SEO Best Practices for SPAs",
  "Web Vitals and Performance",
  "CSS Grid vs Flexbox",
  "Tailwind CSS Utility Classes",
  "CSS-in-JS Solutions",
  "Styled Components vs Emotion",
  "Framer Motion Animations",
  "Three.js and 3D on the Web",
  "WebGL Shaders Explained",
  "Machine Learning in the Browser",
  "TensorFlow.js Introduction",
  "Natural Language Processing Basics",
  "Computer Vision with OpenCV",
  "Blockchain and Smart Contracts",
  "Web3 Development Guide",
  "Solidity Programming for Ethereum",
  "NFT Marketplaces Architecture",
  "Cybersecurity Basics for Developers",
  "OWASP Top 10 Vulnerabilities",
  "Authentication and Authorization",
  "OAuth 2.0 and OpenID Connect",
  "JWT (JSON Web Tokens) Explained",
  "Cryptography Basics",
  "Hashing vs Encryption",
  "Digital Signatures Explained",
  "HTTPS and TLS/SSL",
  "CORS (Cross-Origin Resource Sharing)",
  "Content Security Policy (CSP)",
  "XSS and CSRF Prevention",
  "SQL Injection Vulnerabilities",
  "Rate Limiting Strategies",
  "API Gateway Architecture",
  "Service Mesh with Istio",
  "Infrastructure as Code (IaC)",
  "Terraform vs CloudFormation",
  "Ansible Configuration Management",
  "Prometheus and Grafana Monitoring",
  "ELK Stack for Logging",
  "Datadog Observability",
  "New Relic APM",
  "Sentry Error Tracking",
  "Incident Response Playbook",
  "Site Reliability Engineering (SRE)",
  "Chaos Engineering Practices",
];
