import type { HttpContext } from "zerotal";
import { UploadedFile } from "zerotal/http";
import { Storage } from "zerotal/storage";
import { Auth, AuthMiddleware } from "zerotal/auth";
import type { Project } from "@app/models/Project.ts";
import type { Issue } from "@app/models/Issue.ts";
import { Attachment } from "@app/models/Attachment.ts";
import { StoreAttachmentRequest } from "@app/requests/StoreAttachmentRequest.ts";
import { broadcast } from "@zerotal/broadcasting";
import { AttachmentAdded } from "@app/events/AttachmentAdded.ts";

export const middleware = [AuthMiddleware];

/**
 * POST /projects/:project/issues/:issue/attachments — feature 8.
 *
 * Two names for one file, and the difference is the security property. The
 * reader's filename is recorded and never used as a path; the stored key is
 * `<uuid>.<ext>` generated by `UploadedFile.store`, so an upload cannot pick
 * where its bytes land, cannot traverse out of the directory, and cannot
 * overwrite an earlier upload of the same name.
 *
 * The extension on that key comes from **sniffing the bytes**, not from the
 * declared name — a `.png` whose contents are something else is stored as what
 * it actually is, so the download route's `Content-Type` cannot be talked into
 * serving script as an image.
 *
 * The disk is the default one, which is private: `storage/` is unreachable over
 * HTTP except `storage/public/`. Attachments are read back through the sibling
 * download route, behind the same auth as the issue they belong to.
 */
export async function POST(http: HttpContext): Promise<void> {
  const project = http.params.project as unknown as Project;
  const issue = http.params.issue as unknown as Issue;

  const { file } = await StoreAttachmentRequest.validate();
  const uploader = Auth.user()!;

  const upload = new UploadedFile(file as File);
  const path = await upload.store(`attachments/${issue.id}`, Storage.disk());

  const attachment = new Attachment();
  attachment.issueId = issue.id;
  attachment.uploaderId = uploader.id;
  attachment.path = path;
  attachment.originalName = upload.originalName;
  attachment.mime = upload.mimeType;
  attachment.size = upload.size;
  await attachment.save();

  // `toOthers()` excludes the connection that sent this request — the uploader's
  // own browser is on this socket channel and already has the row from the reload
  // that follows the redirect, so including them would draw the file twice.
  broadcast(
    new AttachmentAdded(issue.id, {
      id: attachment.id,
      name: attachment.originalName,
      mime: attachment.mime,
      size: attachment.size,
      uploader: { name: uploader.name },
      createdAt: attachment.createdAt?.toISOString?.() ?? null,
    }),
  ).toOthers();

  http.flash("success", __("File attached."));
  http.redirect(`/projects/${project.slug}/issues/${issue.id}`, 303);
}
