#!/usr/bin/env bun
/**
 * Snapshot the agent-facing contract of `@zerotal/arch` — the tool names,
 * arguments and result shapes an MCP client binds to.
 *
 *   bun run scripts/mcp-surface.ts            # regenerate the snapshot
 *   bun run scripts/mcp-surface.ts --check    # fail when it is stale
 *
 * ## Why `api-surface.md` is not enough
 *
 * That file records the *typed* export, and for the whole tool system it records
 * one line:
 *
 *     function archTools = (ctx: ToolContext) => ArchTool[]
 *
 * Which is true, and says nothing about the part consumers depend on. Rename
 * `search_docs` to `docs_search`, drop a field from what `routes` returns, or make
 * an optional argument required, and that line is byte-identical: the API-surface
 * gate passes, every test passes, CI is green, and every agent client configured
 * against the server breaks. The names live in the tool definitions as runtime
 * data — `name: "api_surface"` in `apiSurface.ts` — so nothing type-level sees them.
 *
 * This is the same failure shape as `table.boolean()` and `table.string()`: code
 * that compiles, tests that pass, and a contract that only breaks for somebody
 * else. Those were caught by executing against a real server. This is caught by
 * writing the contract down and diffing it.
 *
 * ## What is in it, and why descriptions are
 *
 * Name, title, description, input schema, output schema — everything a tool
 * declares except its handler. Descriptions are included even though rewording one
 * is not a breaking change, because it is the string a model reads when deciding
 * whether to call the tool at all; `ArchTool.description`'s own docblock calls it
 * "the single most load-bearing string in the package". A reworded description
 * changes agent behaviour silently, which is exactly what this file exists to stop.
 * The cost is a regeneration when the wording changes, and the diff says what moved.
 */
import { archTools } from "../packages/arch/src/tools/index.ts";
import { vendoredDocsDir } from "../packages/arch/src/tools/index.ts";

const SNAPSHOT = "packages/arch/mcp-surface.md";
const check = process.argv.includes("--check");

const HEADER = [
  "# MCP tool surface — `@zerotal/arch`",
  "",
  "<!-- Generated by scripts/mcp-surface.ts — do not edit. Regenerate: bun run mcp:surface -->",
  "",
  "The contract an MCP client binds to: tool names, the arguments they accept, and",
  "the shape of what they return. `api-surface.md` records the TypeScript exports and",
  "cannot see any of this — `archTools` is one line there whatever the tools are called.",
  "",
  "A diff in this file is a change every configured agent client will feel.",
  "",
];

/** Stable JSON: keys sorted, so a snapshot diff is a real change and not key order. */
function stable(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, v]) => [k, stable(v)]),
    );
  }
  return value;
}

// The context only decides *where* a tool reads from; the declared contract is the
// same whatever project is being served. A probe that throws is never called here —
// nothing in this script runs a tool, it only reads what each one declares.
const tools = archTools({
  root: "/",
  docsDir: vendoredDocsDir,
  probe: () => {
    throw new Error("mcp-surface never runs a tool");
  },
});

const lines: string[] = [...HEADER];

for (const tool of [...tools].sort((a, b) => a.name.localeCompare(b.name))) {
  lines.push(`## \`${tool.name}\``);
  lines.push("");
  lines.push(`**${tool.title}**`);
  lines.push("");
  lines.push(tool.description.trim());
  lines.push("");
  lines.push("**Arguments**");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(stable(tool.inputSchema), null, 2));
  lines.push("```");
  lines.push("");
  lines.push("**Result**");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(stable(tool.outputSchema), null, 2));
  lines.push("```");
  lines.push("");
}

lines.push(`_${tools.length} tools._`);
lines.push("");

const content = lines.join("\n");
const file = Bun.file(SNAPSHOT);
const existing = (await file.exists()) ? await file.text() : null;

if (existing === content) {
  console.log(`✓ MCP tool surface matches the snapshot (${tools.length} tools).`);
} else if (check) {
  console.error(
    `✖ ${SNAPSHOT} is stale — the agent-facing contract changed.\n` +
      `  Review what moved, then run: bun run mcp:surface`,
  );
  process.exit(1);
} else {
  await Bun.write(SNAPSHOT, content);
  console.log(`✓ Wrote ${SNAPSHOT} (${tools.length} tools).`);
}
