#!/usr/bin/env bun
/**
 * Vendor a handful of brand marks from Simple Icons into `@zerotal/flow-ui`.
 *
 * `@zerotal/auth` ships social login for GitHub, Google and Apple, and a sign-in
 * button wants the provider's actual mark. Lucide dropped brand icons — it keeps
 * stroke-style `github` and `apple`, but has no `google` at all, so a login page
 * could draw two of the three and nothing for the third.
 *
 *   bun run scripts/sync-brands.ts            # fetch and regenerate
 *   bun run scripts/sync-brands.ts --check    # local: the generated file is current
 *
 * **Not a CI gate**, unlike `icons:check`. That one compares two local files and
 * so can run offline; this one has no local source to compare against — the paths
 * live upstream — so gating it would put a network call in front of every build
 * and redden it whenever a CDN blinked. `VERSION` is pinned, so the generated file
 * only moves when someone bumps it deliberately and reviews the diff.
 *
 * ## Why these are fetched and not drawn
 *
 * A brand mark is a specific piece of geometry that people recognise, and an
 * approximation of one reads as a forgery rather than as an icon. These come from
 * [Simple Icons](https://simpleicons.org) (**CC0-1.0**, public domain), so the
 * paths are the real ones and redistributing them carries no licence obligation.
 *
 * **Trademark is a separate matter from copyright.** CC0 waives Simple Icons'
 * rights in the files; it says nothing about the marks themselves, which remain
 * their owners'. Using one to label "Sign in with Google" is nominative use and
 * what the brand guidelines contemplate. Using one as your own logo is not.
 *
 * ## Why only three
 *
 * The full set is 3,000 icons and 15 MB. These are the providers the framework
 * itself has a code path for; anything else an app wants is `registerIcons()`,
 * which is one call and keeps that app's licence its own.
 */
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";

const VERSION = "16.28.0";
const OUT = "packages/flow-ui/src/icons/brands.generated.ts";

/** slug → the name `<Icon>` will answer to. Prefixed, so Lucide's stroke
 *  `github`/`apple` stay reachable and a page picks one style deliberately. */
const BRANDS: Record<string, string> = {
  google: "brand-google",
  github: "brand-github",
  apple: "brand-apple",
};

const check = process.argv.includes("--check");

/** The `d` attribute and title of one Simple Icons SVG. */
async function fetchBrand(slug: string): Promise<{ d: string; title: string }> {
  const url = `https://unpkg.com/simple-icons@${VERSION}/icons/${slug}.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${slug}: ${res.status} from ${url}`);
  const svg = await res.text();

  const d = /\sd="([^"]+)"/.exec(svg)?.[1];
  const title = /<title>([^<]+)<\/title>/.exec(svg)?.[1] ?? slug;
  if (!d) throw new Error(`${slug}: no path data in ${url}`);

  return { d, title };
}

function moduleText(entries: { name: string; slug: string; title: string; d: string }[]): string {
  return [
    "// Auto-generated by scripts/sync-brands.ts — do not edit manually.",
    `// Regenerate with: bun run scripts/sync-brands.ts`,
    "//",
    `// Brand marks from Simple Icons ${VERSION} (CC0-1.0, public domain). The paths are`,
    "// the real ones rather than drawn approximations — see the script for why, and for",
    "// the trademark note that CC0 does not cover.",
    "//",
    '// These are solid marks, not strokes: each carries `fill="currentColor"` because',
    "// `<Icon>` deliberately sets no fill on the wrapper (the bundled Lucide set is a",
    "// stroke set whose bodies fill themselves).",
    "",
    'import type { IconBody } from "./loader.ts";',
    "",
    "/** Brand marks for the social-login providers `@zerotal/auth` supports. */",
    "export const BRAND_ICONS = {",
    ...entries.flatMap((e) => [
      `  /** ${e.title} — simpleicons.org/?q=${e.slug} */`,
      `  ${JSON.stringify(e.name)}: {`,
      `    body: '<path fill="currentColor" d="${e.d}"/>',`,
      `  },`,
    ]),
    "} as const satisfies Record<string, IconBody>;",
    "",
    "/** Every brand mark this package ships. */",
    "export type BrandIconName = keyof typeof BRAND_ICONS & string;",
    "",
  ].join("\n");
}

const entries = [];
for (const [slug, name] of Object.entries(BRANDS)) {
  const { d, title } = await fetchBrand(slug);
  entries.push({ name, slug, title, d });
}
entries.sort((a, b) => a.name.localeCompare(b.name));

const content = moduleText(entries);
const existing = (await Bun.file(OUT).exists()) ? await Bun.file(OUT).text() : null;

if (existing === content) {
  console.log(`✓ ${entries.length} brand mark(s) up to date (Simple Icons ${VERSION}).`);
} else if (check) {
  console.error(`✖ ${OUT} is stale. Run: bun run scripts/sync-brands.ts`);
  process.exit(1);
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  await Bun.write(OUT, content);
  console.log(`✓ Vendored ${entries.length} brand mark(s) from Simple Icons ${VERSION}.`);
}
