#!/usr/bin/env bun
/**
 * Vendor the Lucide icon set into `@zerotal/flow-ui`, so `<Icon name="inbox" />`
 * works in a fresh app with nothing installed and nothing configured.
 *
 * The alternative — asking each app to `bun add @iconify-json/lucide` — is the
 * kind of setup step the framework exists to remove, and it buys nothing here:
 * icons are rendered on the server, so the set never reaches a browser and there
 * is no bundle to keep small. It costs ~570 KB in the package (~87 KB packed) and
 * saves every app the install.
 *
 *   bun run scripts/sync-icons.ts            # upgrade: fetch the set, regenerate names
 *   bun run scripts/sync-icons.ts --check    # CI: names still match the vendored bodies
 *
 * **`--check` never touches the network**, which is the difference between a gate
 * and a nuisance. What it verifies is that `names.generated.ts` still describes
 * `lucide.json` — a local invariant, broken only by someone editing one and not
 * the other. Checking against npm instead would turn every upstream release into
 * a red build on a commit that changed nothing, and a gate that cries wolf is one
 * people learn to force through.
 *
 * Upgrading the set is therefore a deliberate act: run it with no flags, review
 * the diff, commit it. That is the same bargain `arch-docs.ts` makes.
 *
 * ## Licensing is why this set and not another
 *
 * Lucide is **ISC** — redistributable with its notice, which `LICENSE-ICONS.md`
 * carries. Most icon sets are not so easy: Font Awesome Free is CC BY 4.0, usable
 * only with attribution the *app* would have to display, and Font Awesome Pro may
 * not be redistributed at any price. Vendoring either would relicense someone
 * else's artwork on behalf of every app that installed Flow. An app that wants a
 * set we cannot ship still has `registerIcons()`.
 */
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";

const PACKAGE = "@iconify-json/lucide";
const DATA_FILE = "packages/flow-ui/src/icons/lucide.json";
const NAMES_FILE = "packages/flow-ui/src/icons/names.generated.ts";
const LICENSE_FILE = "packages/flow-ui/LICENSE-ICONS.md";

const check = process.argv.includes("--check");

interface IconifyJSON {
  prefix: string;
  icons: Record<string, { body: string; width?: number; height?: number }>;
  aliases?: Record<string, { parent: string; width?: number; height?: number }>;
  width?: number;
  height?: number;
  lastModified?: number;
}

interface Info {
  name: string;
  total: number;
  author: { name: string; url: string };
  license: { title: string; spdx: string; url: string };
}

/** Fetch the published tarball and read the two files we care about out of it. */
async function fetchSet(): Promise<{ icons: IconifyJSON; info: Info; version: string }> {
  const meta = (await (await fetch(`https://registry.npmjs.org/${PACKAGE}/latest`)).json()) as {
    version: string;
    dist: { tarball: string };
  };

  // `os.tmpdir()` and not `$TMPDIR`, which is unset on Windows — the fallback was
  // `.`, so the first run unpacked the tarball into the repository root and left it
  // there for `format:check` to trip over.
  const tmp = join(tmpdir(), `zt-icons-${meta.version}`);
  mkdirSync(tmp, { recursive: true });

  await Bun.write(join(tmp, "set.tgz"), await (await fetch(meta.dist.tarball)).arrayBuffer());

  // `tar` ships with Git for Windows and every CI image; extracting through it
  // avoids a tar/gzip dependency for a script that runs by hand.
  //
  // Run from `tmp` with a bare filename rather than passing an absolute path: GNU
  // tar reads the `C:` in a Windows path as a remote host and tries to ssh to it
  // ("Cannot connect to C: resolve failed"). `--force-local` also fixes that and is
  // GNU-only, which would break the same script on macOS's bsdtar.
  const proc = Bun.spawnSync(["tar", "-xzf", "set.tgz"], { cwd: tmp });
  if (proc.exitCode !== 0) {
    throw new Error(`tar failed: ${new TextDecoder().decode(proc.stderr)}`);
  }

  return {
    icons: (await Bun.file(`${tmp}/package/icons.json`).json()) as IconifyJSON,
    info: (await Bun.file(`${tmp}/package/info.json`).json()) as Info,
    version: meta.version,
  };
}

/**
 * Every name the set answers to, icons and aliases alike, sorted.
 *
 * Aliases are included rather than resolved away: they are the names people
 * actually reach for after a rename upstream, and leaving them out would make
 * `<Icon name="home" />` a type error while `house` worked.
 */
function allNames(set: IconifyJSON): string[] {
  return [...Object.keys(set.icons), ...Object.keys(set.aliases ?? {})].sort();
}

function namesModule(names: string[], version: string): string {
  return [
    "// Auto-generated by scripts/sync-icons.ts — do not edit manually.",
    `// Regenerate with: bun run scripts/sync-icons.ts`,
    "//",
    `// Every icon in the vendored Lucide set (${PACKAGE}@${version}), icons and`,
    "// aliases alike. A union rather than `string` so a typo in an icon name is a",
    "// compile error and not a silently blank space on the page.",
    "",
    "/** Every icon name the bundled set provides. */",
    "export type LucideIconName =",
    ...names.map((n) => `  | ${JSON.stringify(n)}`),
    "  ;",
    "",
  ].join("\n");
}

function licenceNote(info: Info, version: string): string {
  return [
    "# Icon licence",
    "",
    `The icons bundled in \`src/icons/lucide.json\` are **${info.name}**, vendored from`,
    `[\`${PACKAGE}\`](https://www.npmjs.com/package/${PACKAGE}) at version \`${version}\`.`,
    "",
    `- **Licence:** ${info.license.title} (\`${info.license.spdx}\`) — <${info.license.url}>`,
    `- **Authors:** ${info.author.name} — <${info.author.url}>`,
    `- **Icons:** ${info.total}`,
    "",
    "Lucide is ISC-licensed, which is why it can be shipped inside this package at all.",
    "Redistributing it carries the notice above and nothing else — no attribution is",
    "required in your application's UI.",
    "",
    "Icons your app registers itself through `registerIcons()` are yours, and their",
    "licence is between you and whoever drew them.",
    "",
    "_This file is generated by `scripts/sync-icons.ts`._",
    "",
  ].join("\n");
}

async function writeOrCheck(path: string, content: string): Promise<boolean> {
  const file = Bun.file(path);
  const existing = (await file.exists()) ? await file.text() : null;
  if (existing === content) return false;

  if (!check) {
    mkdirSync(dirname(path), { recursive: true });
    await Bun.write(path, content);
  }
  return true;
}

/** The version the vendored copy came from, read back out of the generated header. */
async function vendoredVersion(): Promise<string> {
  const header = await Bun.file(NAMES_FILE).text();
  return /@iconify-json\/lucide@([^)\s]+)/.exec(header)?.[1] ?? "unknown";
}

if (check) {
  // Offline by design — see the module docblock. Regenerate the names from the
  // bodies already on disk and compare; nothing else here is derived.
  const vendored = (await Bun.file(DATA_FILE).json()) as IconifyJSON;
  const names = allNames(vendored);
  const version = await vendoredVersion();

  if (await writeOrCheck(NAMES_FILE, namesModule(names, version))) {
    console.error(
      `✖ ${NAMES_FILE} does not match ${DATA_FILE}.\n` +
        `  Run: bun run scripts/sync-icons.ts --names`,
    );
    process.exit(1);
  }

  console.log(
    `✓ Icon names match the vendored set (${names.length} names, ${PACKAGE}@${version}).`,
  );
} else if (process.argv.includes("--names")) {
  // Regenerate the union from what is already vendored, without an upgrade.
  const vendored = (await Bun.file(DATA_FILE).json()) as IconifyJSON;
  const names = allNames(vendored);
  await writeOrCheck(NAMES_FILE, namesModule(names, await vendoredVersion()));
  console.log(`✓ Regenerated ${names.length} names from the vendored set.`);
} else {
  const { icons, info, version } = await fetchSet();
  const names = allNames(icons);

  // Stored formatted so a diff on an upgrade is readable — which body changed,
  // which name appeared — rather than one 570 KB line that reviews as "everything".
  await writeOrCheck(DATA_FILE, JSON.stringify(icons, null, 2) + "\n");
  await writeOrCheck(NAMES_FILE, namesModule(names, version));
  await writeOrCheck(LICENSE_FILE, licenceNote(info, version));

  console.log(
    `✓ Vendored ${names.length} names from ${PACKAGE}@${version} ` +
      `(${Object.keys(icons.icons).length} icons, ${Object.keys(icons.aliases ?? {}).length} aliases).`,
  );
}
