import { createInertiaApp } from "@inertiajs/react";
import { createRoot } from "react-dom/client";

// pages.generated.ts is auto-generated by: bun zerotal.ts inertia:build
// It maps component names to dynamic import thunks for code splitting.
// Do NOT import pages statically — that defeats code splitting.
import { pages } from "./pages.generated.ts";

createInertiaApp({
  // Inertia calls this to load a page component.
  // Dynamic import thunks enable per-page code splitting.
  // Bun only loads the chunk for the current page — not all 150 pages.
  resolve: async (name: string) => {
    // `pages` is keyed by literal page name (it is written with `satisfies`, so
    // the server can check `Inertia.render("Users/Index", …)` against it). The
    // name Inertia hands us is a runtime string, so this one lookup widens it.
    const thunk = (pages as Record<string, () => Promise<unknown>>)[name];
    if (!thunk) {
      throw new Error(
        `[Zerotal Inertia] Page not found: "${name}". Run: bun zerotal.ts inertia:build`,
      );
    }
    const mod = await thunk();
    return (mod as { default: unknown }).default;
  },
  setup({ el, App, props }: { el: Element; App: unknown; props: unknown }) {
    createRoot(el).render(
      // @ts-expect-error — App is typed as unknown in the stub
      <App {...(props as object)} />,
    );
  },
});
