// Auto-generated by @zerotal/core — do not edit manually.
// Regenerate with: bun zt route:types
//
// Every named route, the URL pattern it compiles to, and the HTTP method it
// answers on. `route()` reads ROUTES through declaration merging, so an unknown
// name or a missing :param is a compile error; `action()` also reads METHODS, so
// a form cannot submit a route with the wrong verb.
// Commit this file: editors and CI need it without booting the app.

export const ROUTES = {
  activity: "/activity",
  dashboard: "/dashboard",
  "forgot-password": "/forgot-password",
  "forgot-password.store": "/forgot-password",
  home: "/",
  "locale.store": "/locale",
  login: "/login",
  "login.store": "/login",
  "logout.store": "/logout",
  profile: "/profile",
  "profile.appearance.store": "/profile/appearance",
  "profile.locale.store": "/profile/locale",
  "profile.password.store": "/profile/password",
  "profile.store": "/profile",
  projects: "/projects",
  "projects.board.show": "/projects/:project/board",
  "projects.issues.attachments.show": "/projects/:project/issues/:issue/attachments/:attachment",
  "projects.issues.attachments.store": "/projects/:project/issues/:issue/attachments",
  "projects.issues.comments.store": "/projects/:project/issues/:issue/comments",
  "projects.issues.edit.show": "/projects/:project/issues/:issue/edit",
  "projects.issues.edit.store": "/projects/:project/issues/:issue/edit",
  "projects.issues.new.show": "/projects/:project/issues/new",
  "projects.issues.new.store": "/projects/:project/issues/new",
  "projects.issues.show": "/projects/:project/issues/:issue",
  "projects.show": "/projects/:project",
  register: "/register",
  "register.store": "/register",
  "reset-password": "/reset-password",
  "reset-password.store": "/reset-password",
} as const;

export const METHODS = {
  activity: "GET",
  dashboard: "GET",
  "forgot-password": "GET",
  "forgot-password.store": "POST",
  home: "GET",
  "locale.store": "POST",
  login: "GET",
  "login.store": "POST",
  "logout.store": "POST",
  profile: "GET",
  "profile.appearance.store": "POST",
  "profile.locale.store": "POST",
  "profile.password.store": "POST",
  "profile.store": "POST",
  projects: "GET",
  "projects.board.show": "GET",
  "projects.issues.attachments.show": "GET",
  "projects.issues.attachments.store": "POST",
  "projects.issues.comments.store": "POST",
  "projects.issues.edit.show": "GET",
  "projects.issues.edit.store": "POST",
  "projects.issues.new.show": "GET",
  "projects.issues.new.store": "POST",
  "projects.issues.show": "GET",
  "projects.show": "GET",
  register: "GET",
  "register.store": "POST",
  "reset-password": "GET",
  "reset-password.store": "POST",
} as const;

/** The generated route table, as a type. */
export type Routes = typeof ROUTES;

/** The HTTP method each named route answers on. */
export type RouteMethods = typeof METHODS;

declare module "@zerotal/core" {
  interface RouteRegistry extends Routes {}
  interface RouteMethodRegistry extends RouteMethods {}
}
